### ISSUE TITLE
similar to level-js

### ISSUE THREAD

**Issue by timoxley** [mozilla/localForage#15]
seen https://github.com/maxogden/level.js?

Perhaps you could consider some collaboration here or at least a mention in the readme since these are basically the same api except that level-js conforms to an interface that allows it to work with much of [the existing leveldb ecosystem](https://github.com/rvagg/node-levelup/wiki/Modules).

**Comment by tofumatt** [comment]
After three years of not implementing this–I'm thinking we won't. I'd take a PR, but I'll say there's not enough interest in this when there are more pressing patches.

Feel free to re-open if anyone disagrees!

**Comment by nolanlawson** [comment]
FWIW PouchDB also dropped level.js support in v5 (it was available via an add-on adapter).
