### ISSUE TITLE
Try writing some code using ES6

### ISSUE THREAD

**Issue by tofumatt** [mozilla/localForage#158]
It might be nice to experiment with some ES6 goodness in localForage. And with #157, we can nicely transform it to ES5 for distribution.

**Comment by thgreasi** [comment]
Do you have any specific transpiler in mind to recommend?
I would go with traceur for start, since it has been tested well enough by the angular community.

Should we also emit an es5 folder in the dist directory (or somewhere else)? Should the es5 files be included in the bower package?

**Comment by stephanebachelier** [comment]
There is also [babeljs](https://babeljs.io) which was previously 6to5.

--
Stéphane Bachelier,
Tél. 06 42 24 48 09
B8A5 2007 0004 CDE4 5210  2317 B58A 335B B5A4 BFC2

2015-02-20 19:20 GMT+01:00 Thodoris Greasidis <notifications@github.com>:

**Comment by thgreasi** [comment]
After some comparison of [babel](https://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=class%20Greeter%20{%0A%20%20constructor%28message%29%20{%0A%20%20%20%20this.message%20%3D%20message%3B%0A%20%20}%0A%0A%20%20greet%28%29%20{%0A%20%20%20%20var%20element%20%3D%20document.querySelector%28%27%23message%27%29%3B%0A%20%20%20%20element.innerHTML%20%3D%20this.message%3B%0A%20%20}%0A}%3B%0Avar%20test%20%3D%20new%20Greeter%28%27test%27%29%3B) and [traceur](http://google.github.io/traceur-compiler/demo/repl.html#class%20Greeter%20{%0A%20%20constructor%28message%29%20{%0A%20%20%20%20this.message%20%3D%20message%3B%0A%20%20}%0A%0A%20%20greet%28%29%20{%0A%20%20%20%20var%20element%20%3D%20document.querySelector%28%27%23message%27%29%3B%0A%20%20%20%20element.innerHTML%20%3D%20this.message%3B%0A%20%20}%0A}%3B%0Avar%20test%20%3D%20new%20Greeter%28%27test%27%29%3B) I spotted some differences.

I think babel is using [object property definition](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty). Is this es3 polyfillable?

**Comment by stephanebachelier** [comment]
@thgreasi for older browser you must use the [es5-shim](https://github.com/es-shims/es5-shim) and the babel polyfill.

There is a section at the end of [babel caveats page](http://babeljs.io/docs/usage/caveats/)

> By default, when using modules with babel a non-enumerable __esModule property is exported. This is done through the use of Object.defineProperty which is unsupported in IE8 and below. A workaround for this is to [enable loose mode - modules](http://babeljs.io/docs/usage/caveats/6to5.org/docs/usage/loose/#modules).

**Comment by thgreasi** [comment]
@stephanebachelier :+1: it look like that loose mode produces cleaner code without the need of Object.defineProperty.

**Comment by thgreasi** [comment]
Just created [a branch to test babel](https://github.com/thgreasi/localForage/tree/es6-babel).
All the tests pass and the generated code is as readable are the original non es6.
The most annoying thing was jshint and jscs on es6 code.
Also, the component build does not like es6 so I had to keep a separate es5src.

As side notes:
* Didn't test it on IE8 (maybe next week)
* It places a global `"use strict"` statement and a global `_classCallCheck` object.
  * Maybe I should wrap all the generated code in an IIFE.

**Comment by tofumatt** [comment]
So far that looks good, I like being able to use the `class` for `LocalForage` :+1: 

I'm moving right now (Canada to the UK!) so I can't code/test much stuff but happy to review things later, whenever you can get to them :+1:

**Comment by thejameskyle** [comment]
Hi I'm a Babel contributor. @thgreasi if you want to leave out the `"use strict"` you can [blacklist it](http://babeljs.io/docs/usage/transformers/other/strict/). If you want to see an excellent example of how to write a library with Babel check this out: https://github.com/babel/babel-library-boilerplate.

If you need any other help let me know or ask in our support chat: https://gitter.im/babel/babel

**Comment by thgreasi** [comment]
Thanks @thejameskyle :+1:
Atm I'm looking at custom module formatters.
UMD looks very similar to what we currently do to fetch driver modules, except that we also look at the global object as well.

**Comment by thejameskyle** [comment]
We're looking to improve that in the future, right now if you need a global in the UMD you can use [esperanto](http://esperantojs.org) like the boilerplate does.

**Comment by thgreasi** [comment]
Thanks, I will take a look at it asap.

**Comment by thgreasi** [comment]
@thejameskyle We do import some files programmatically and so I was
thinking about writing a Transformer to change expressions like:

System.import('aDriver')

Into something like Esperanto/UMD+Globals.

Does this actually make any sense?

**Comment by RangerMauve** [comment]
System.import is apparently the future since it's being officially standardized. I'd give a -1 to moving away from that.

**Comment by thgreasi** [comment]
I thought it got removed in the [April's es6 draft](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-loader-objects)!?!?!?
(As you can see the #sec-loader-objects is missing from the current page, as well as any System.import reference.)

**Comment by RangerMauve** [comment]
Huh, good point. I hadn't heard about that yet.

**Comment by thejameskyle** [comment]
I don't know how you'd dynamically load something in a UMD. You could certainly do it if you were using a module loader like system.js.

**Comment by megawac** [comment]
UMD supports AMD which is all about dynamic loading no?

**Comment by thejameskyle** [comment]
Yeah but the point of the UMD is to work in all environments (AMD, Common.js, Globals).

**Comment by thgreasi** [comment]
[The current UMD formatter](https://babeljs.io/docs/usage/modules/#umd) does a great job in **creating modules that can be imported** using any/many different module systems.
However it does not specify a way on how your code should be written when it needs to import sub-modules

LocalForage tries to [dynamically load the drivers](https://github.com/mozilla/localForage/blob/b88deae8495a60b2ad92eef97e5c2be23d185d1f/src/localforage.js#L329-L350) and [the common Serializer](https://github.com/mozilla/localForage/blob/5e0df09bce8f0316369c05a867b0d5d7b836fb8f/src/drivers/websql.js#L59-L70), by guessing the available module system available. It currently supports global and commonjs/browserify imports as well as async loading with AMD/requirejs. That's so that the user can benefit the most of his module loader of choice, no matter what he is using (RequireJS/Browserify/GlobalNamespace).

I was discussing about creating a Transformer (if there isn't one already) that would allow **to programmatically import UMD modules** no matter what the module loading scheme is used at runtime.

I would expect that such a Transformer would change expressions like:
```js
System.import('aDriver').then(...);
```
To something like:
```js
new Promise(function(resolve, reject)){
    if (System && System.import && typeof System.import === "function") {
        System.import('aDriver', resolve);
    } else if (typeof define === "function" && define.amd) {
        require(['aDriver'], resolve);
    } else if (typeof exports !== "undefined") {
        resolve(require('aDriver'));
    } else {
        resolve(globalObject['aDriver']);
    }
}).then(...);
```

I guess I should probably move this discussion to the babel repo...

PS: I chose `System.import` as the default way to programmatically import a module, because it looks like it's the the most promising to become a standard (at some point in the future).
