### ISSUE TITLE
Add support for transactions/atomic operations?

### ISSUE THREAD

**Issue by tofumatt** [mozilla/localForage#17]
It would be cool to be able to increment values and perform types of atomic operations. Can this be done without sacrificing the current API? Or by enabling an `ADVANCED_MODE` or some such?

**Comment by tofumatt** [comment]
Right now this seems pretty out-of-scope for localForage. An entire transaction solution would be heavyweight and not in the spirit of the simplistic nature of localForage.

I think I'll close this for now, but a PR would be welcome in the future.

**Comment by jampy** [comment]
sorry, but why is this heavywheight? both WebSQL and IndexedDB support transactions natively AFAIK, so localforage could just use them.

Okay, this won't work with localStorage driver, but even then an `ADVANCED_MODE` flag or similar (as proposed by someone else) could restrict usage to the other IndexedDB/WebSQL drivers.

**Comment by tofumatt** [comment]
As mentioned, I would be open to a pull request but especially as we want version 1.0 to support localStorage, we would need to support transactions for it. Or this would have to be a feature we land in a 2.0, when maybe we won't use localStorage anymore.

**Comment by ccorcos** [comment]
Just wanted to chime in with my use-case. When a user is offline, we save database entries in the browser. When the user comes back online, we sync that up with the server. However, since browser windows share state, without transactions, we can end up committing things twice...

**Comment by shmilyoo** [comment]
really need atomic transaction api.
Many scenarios will encounter this situation of read and write conflicts
