### ISSUE TITLE
Unable to create multiple tables within a single database

### ISSUE THREAD

**Issue by kriswillis** [mozilla/localForage#204]
When attempting to create a second table within a single database, nothing happens; the table isn't created and the promise or callback is not fired on any call to setItem, for example.

I'm experiencing this issue with Google Chrome (35.0.1916.153) and IndexedDB.

An example of the issue can be viewed here: http://jsfiddle.net/kriswillis/uK3Qz/ - After loading the fiddle, "table1" is created under the "myApp" database, when changing the page variable to 2 and re-running, "table2" is not created.

**Comment by bradgreens** [comment]
A year later I have this problem too - hoping to have 3-4 tables in my app.

**Comment by ktown007** [comment]
I want to do the same. This looks to work:

<script>
var items = localforage.createInstance({ name: "mydatabasename"  });
items.config({ storeName: 'items'});
var config = localforage.createInstance({ name: "mydatabasename" });
config.config({ storeName: 'config'});;

items.setItem("foo", {"id":123 , "name":"bar" } );
config.setItem( "user" , "dilbert" );
</script>

**Comment by mbalyaba** [comment]
"var items = localforage.createInstance({ name: "mydatabasename" , storeName: "items" });
var config = localforage.createInstance({ name: "mydatabasename" , storeName: "config" });

items.setItem( "foo", {"id":123 , "name":"bar" } );
config.setItem( "user" , "dilbert" );"
Doesn't work for me.
It creates only "items" ObjectStore

**Comment by mbalyaba** [comment]
any updates?

**Comment by tofumatt** [comment]
No updates from me, but if someone could find the reason for the bug and patch it I could certainly review it quickly.

I have less time to hunt down bugs right now so I can't give a date on this, though I understand it's a frustrating issue.

**Comment by mbalyaba** [comment]
for current implementation it seems like the only workaround to create new ObjectStore inside current database is to increase db version.

var items = localforage.createInstance({ name: "testdatabase" , storeName: "items" });
items.setItem( "foo", {"id":123 , "name":"bar" } );

var config = localforage.createInstance({ name: "testdatabase" , storeName: "config", version: 2});
config.setItem( "user" , "dilbert" );

But I'm not sure that it is a good solution.

**Comment by sebweaver** [comment]
@mbalyaba Your workaround shouldn't be necessary because this issue (similar to #342) has been fixed by https://github.com/mozilla/localForage/pull/452 and released in 1.3.0 (and 1.3.1 for Ember).

Which version do you use? Do you have any error in the console?

**Comment by mbalyaba** [comment]
Oh, sorry, my version is 1.2.2. In this version I have an error about non exist ObjectStore(for second instance).
Anyway if issue is fixed then it is a very very good news!
I will update.
Thank you!

**Comment by sebweaver** [comment]
@tofumatt I think we should close this issue, since it's related to #342 which has been fixed.

**Comment by tofumatt** [comment]
Ah okay, sounds good.

- tofumatt (Sent from mobile)

**Comment by sebweaver** [comment]
@mbalyaba You may now experience the following issue with Chrome on first startup:

    Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

If so, please refer to #492 in which it has been recently reported.

**Comment by owenfar** [comment]
> I want to do the same. This looks to work:
> 
> var items = localforage.createInstance({ name: "mydatabasename" , storeName: "items" });
> var config = localforage.createInstance({ name: "mydatabasename" , storeName: "config" });
> 
> items.setItem( "foo", {"id":123 , "name":"bar" } );
> config.setItem( "user" , "dilbert" );

Why isn't this included in the documentation @tofumatt & @sebweaver ? I was very close to switching to another library until I finally found this issue.

I've read everything, did I miss something? It would be nice and clear to have a section like "Create multiple tables in one DB instance".

Thanks a lot!

**Comment by tofumatt** [comment]
@owenfar There is documentation about multiple instances on the main API docs page, linked in the repo: https://localforage.github.io/localForage/#multiple-instances

Is there something missing from there for you? For what it's worth, I'm in the process of redoing the docs and the website, but for now I think the docs there cover multiple instances.

**Comment by owenfar** [comment]
@tofumatt That section about multiple-instances is very clear, but multiple instances act as different "databases". It is not shown or is very clear to me that in an instance we can create different stores. From the docs I thought that I could only created different DBs, and not different storeNames (tables). 

I think that for newcomers it would be very beneficial to have another section called "Create multiple stores in the same instance" and show a clear example of that, same as I quoted in the previous comment, or something like:

`const dbName = 'databaseName';

  // Create table 1 in databaseName
  _os_db.states = localforage.createInstance({
      driver      : localforage.INDEXEDDB,
      name        : dbName,
       storeName   : 'tableOne',
       description : '...'
  });

  // Create table 2 in databaseName
  _os_db.states = localforage.createInstance({
      driver      : localforage.INDEXEDDB,
      name        : dbName,
       storeName   : 'tableTwo',
       description : '...'
  });`

Do you think this would be better?

**Comment by tofumatt** [comment]
That looks great! Would you mind submitting a PR with those changes? 😄

**Comment by owenfar** [comment]
@tofumatt Awesome. Sure, I'll do that now :)

**Comment by MiguelQueiroz** [comment]
> @tofumatt That section about multiple-instances is very clear, but multiple instances act as different "databases". It is not shown or is very clear to me that in an instance we can create different stores. From the docs I thought that I could only create different DBs, and not different storeNames (tables).
> 
> I think that for newcomers it would be very beneficial to have another section called "Create multiple stores in the same instance" and show a clear example of that, same as I quoted in the previous comment, or something like:
> 
> ```
> const dbName = 'databaseName';
> 
> // Create table 1 in databaseName
> var tableOne = localforage.createInstance({
>       driver      : localforage.INDEXEDDB,
>       name        : dbName,
>       storeName   : 'tableOne',
>       description : '...'
> });
> 
> // Create table 2 in databaseName
> var tableTwo = localforage.createInstance({
>       driver      : localforage.INDEXEDDB,
>       name        : dbName,
>       storeName   : 'tableTwo',
>       description : '...'
> });
> ```
> 
> Do you think this would be better?

By the way does this works? Have you tested? I can not make it work... Used the example above... It only created 1 storeName inside the DB.

**Comment by owenfar** [comment]
@MiguelQueiroz Yes it should work, perhaps something else is going wrong. Can you share what you did so that we can better help you?

**Comment by MiguelQueiroz** [comment]
> @MiguelQueiroz Yes it should work, perhaps something else is going wrong. Can you share what you did so that we can better help you?

yes, try this.

So the databases are only generated, when they are followed or called by a setItem, meanwhile they are not created. Which is very confusing, because the docs don't say that.


https://jsfiddle.net/fvx9kao3/

**Comment by owenfar** [comment]
Is it a problem for you that the DB is not created until an item exists? Not sure if this is the normal behaviour, but if the code works when an item is added, there's not much I can do for you. Perhaps you can open another issue as it's not related to this one. Best, Owen
