### ISSUE TITLE
Chrome 37 IndexedDB stores incorrect content type for blobs

### ISSUE THREAD

**Issue by nolanlawson** [mozilla/localForage#241]
Hello from PouchDB. :)

Just a heads up, in case you weren't aware of this bug: https://github.com/pouchdb/pouchdb/issues/2701 and https://code.google.com/p/chromium/issues/detail?id=408120.

From Chrome 38+, blobs will be stored just fine, exactly like IE and Firefox. In the meantime, 37 is out there in the wild, and it's got this bug. If you'd like to detect blob support, [here's the code we use](https://github.com/pouchdb/pouchdb/blob/eae1b9da321c6bdb91ec0f79bdc33487a7555117/lib/adapters/idb.js#L1239-L1274), which should work on Firefox, IE, and Chrome 36-38.

**Comment by sheppard** [comment]
I came across the lack of Blob support in my own testing (see #380) on an Android 4.4.4 Samsung device (UA string claims "Chrome/28").  I worked around it in my vendored copy of localForage with a [UA sniff](https://github.com/wq/wq.app/commit/db26e665ef2b5ea77d1b9f179bab38692b3e8f6a#diff-f23e060863b5229048e4640b06ad0bb6R2162) marking `IndexedDB` as unsupported in any Chrome less than 38.  This effectively makes `localForage` use the `WebSQL` backend, which serializes blobs for storage.  I suppose an alternative would be to enable the serializer for the `IndexedDB` driver in this case (which would be effectively the same as to the PouchDB approach).  

I didn't submit a PR as I'm not the UA sniff is the right approach (better approaches have already been listed), and I assume not everyone finds `Blob` support mission-critical as I do.

**Comment by nolanlawson** [comment]
@sheppard Yeah sorry, I did not follow up with the localForage fix after reporting this. But basically our "blob support" check looks like this now: https://github.com/pouchdb/pouchdb/blob/1093c845bac9550baf8b0394d59fed3e14efe185/lib/adapters/idb/idb-blob-support.js

Reason being, there were actually more bugs that popped up since v38, and blobs are only reeeeaaally supported in v43 (see [state of binary data in the browser](https://github.com/nolanlawson/state-of-binary-data-in-the-browser#readme) for the gory details).

**Comment by nolanlawson** [comment]
Found some time tonight, so here we go: https://github.com/mozilla/localForage/pull/382 :smiley:

In retrospect, I'm kind of flabbergasted at the number of hacks necessary to get blobs to work in IndexedDB. Might make more sense to just take that `_checkBlobSupport()` function and use it to downgrade to WebSQL... :expressionless:

**Comment by bitinn** [comment]
Wow nice work, also amazed by the number of problems with blob in IndexedDB, a good read: https://github.com/nolanlawson/state-of-binary-data-in-the-browser

**Comment by sheppard** [comment]
Yes, thanks for all your work in this area, @nolanlawson.

**Comment by nolanlawson** [comment]
this has been fixed for awhile
