### ISSUE TITLE
Add API docs for new multiple storage feature

### ISSUE THREAD

**Issue by tofumatt** [mozilla/localForage#260]
Since merging in #253, we should add some docs for it. :smile:

**Comment by RangerMauve** [comment]
Would the docs just be a section in [here](https://github.com/mozilla/localForage/blob/master/site/index.md)? Are there unit tests that cover the functionality that can be documented?

**Comment by RangerMauve** [comment]
Going to assume that the stuff covered in the tests added [here](https://github.com/thgreasi/localForage/commit/292c4e59b9c8a7b4a813b7b67fa64a2e0147a729) is the only thing that needs to be documented.

**Comment by tofumatt** [comment]
Yeah, that should be it really. Let me know if you’re gonna work on it and I’ll keep my eye out for a PR!

**Comment by RangerMauve** [comment]
I'm not 100% sure yet, but I'll post here in the evening to confirm.

**Comment by tofumatt** [comment]
Awesome! I’m in Greece right now so I might not get to it until tomorrow morning European time, but I’ll look at it ASAP :-)

Thank you!

**Comment by thgreasi** [comment]
@tofumatt Is there any event you are going to participate?
It has been some time since my last mozilla sponsored event :disappointed:

**Comment by tofumatt** [comment]
@thgreasi I was just at an MDN Hack Day in Berlin, but it was pretty small. Fun fact, I'm in Athens until May, so maybe I could see about getting something together later in the month/early May. You should send me an email if you're near Athens and think it would work :smile:

**Comment by RangerMauve** [comment]
Thar she blows, I guess

**Comment by doesntgolf** [comment]
Sorry to ping an old issue, but it looks like the updated documentation never actually made it onto [mozilla.github.io/localForage](https://mozilla.github.io/localForage/)? I'm guessing it just needs to be added [here](https://github.com/mozilla/localForage/blob/gh-pages/index.html). I can throw together a PR for it if needed. At a quick glance the website looks to also be missing the `supports` method from [here](https://github.com/mozilla/localForage/blob/master/site/index.md#supports), so maybe there's more missing as well?

**Comment by tofumatt** [comment]
Yeah, building the docs has become an issue lately and I think they're out
of date. I have to fix how they're generated (we have an issue open for it
but I'm on my phone right now and can't find it).

I'll prioritise getting that solved to update the docs site.
- tofumatt
