### ISSUE TITLE
key function in localStorage

### ISSUE THREAD

**Issue by ocombe** [mozilla/localForage#280]
I'm not sure if we should fix this, but in localStorage the key function will return the key number n from storage without taking the prefix into account.
The function is:
```js
function key(n, callback) {
	var self = this;
	var promise = new Promise(function(resolve, reject) {
		self.ready().then(function() {
			var dbInfo = self._dbInfo;
			var result;
			try {
				result = localStorage.key(n);
			} catch (error) {
				result = null;
			}
			// Remove the prefix from the key, if a key is found.
			if (result) {
				result = result.substring(dbInfo.keyPrefix.length);
			}
			resolve(result);
		}).catch(reject);
	});
	executeCallback(promise, callback);
	return promise;
}
```

Let's say that we have 5 keys in localStorage, 3 are from localForage. If we use the method keys we might get the keys 1, 2 and 5, but the index won't be the same as the ones we might be using for the method key.

It shouldn't be a really big problem since you can use the method keys to get all the localForage keys anyway, but maybe we should put a warning somewhere ?
We could also change the function to get the key at index n from localForage keys (by using the keys function to get all the keys and then extracting the n one).
What do you think ?

**Comment by tofumatt** [comment]
Going to close this as we'll be removing `key()` in the future.
