### ISSUE TITLE
not working with webpack require

### ISSUE THREAD

**Issue by ericfong** [mozilla/localForage#290]
after bower install localforage

and run webpack

promise module are missing

Seems localforage using some other module system?

**Comment by MattKunze** [comment]
I created a simple repo to play around with ways to get this working well. `script-loader` works, but isn't really an ideal way to do it:

webpack.config.js:

```javascript
  resolve: {
    alias: { localforage: 'localforage/dist/localforage.min' }
  }
```

and then use `require('script!localforage');`

I got close to having it work by default by using

```javascript
  resolve: {
    alias: { localforageSerializer: 'localforage/src/utils/serializer' }
  }
```

this generates warnings because of the wildcard AMD requires, but it actually loads despite some console errors:

```
WARNING in ./~/localforage/src/localforage.js
Critical dependencies:
332:20-336:22 the request of a dependency is an expression
 @ ./~/localforage/src/localforage.js 332:20-336:22
```

Now to figure out how to get it to skip those entries and it should load more cleanly.

**Comment by MattKunze** [comment]
Forgot to include a link to the playground repo: https://github.com/MattKunze/localforage-webpack

**Comment by srph** [comment]
@MattKunze Have you made it work?

**Comment by MattKunze** [comment]
We're using [script-loader](https://github.com/webpack/script-loader) to load the packaged version, that's the only thing I've been able to get to work so far. You might be able to simplify the config and just use `require('script!localforage/dist/localforage.min')`

I was working with PouchDB and it has similar code that produces the same problems (pouchdb/pouchdb#3319). Another potential solution is to not use `script-loader`, but add a `noParse` option for the script in the webpack config.

**Comment by marcucio** [comment]
I made a fix here that might fix this too, we might have to modify my pull request. I added a check for if require exists but we might have to check if require is actually a function:

https://github.com/mozilla/localForage/issues/365

**Comment by MattKunze** [comment]
I'll give it a shot, but I'm not sure it will make any difference. webpack looks at the parsed AST for the script and processes any `require` statements it sees as far as I know. So changing the `if` statement doesn't change the fact that the block still has a require statement it can't resolve. If there was someway for webpack to know that block will always be skipped in a particular environment that would potentially fix it.

**Comment by stephenrs** [comment]
I haven't looked too closely, but isn't UMD the answer here? Seems this wheel has already been invented.

**Comment by stephenrs** [comment]
I found success with webpack 1.10.1 + localForage 1.2.2 by using this wrapper library (asyncstorage): https://github.com/alekseykulikov/storage (which I was using anyway). Just make sure that either A: the only copy of localForage installed in your project is the one that comes bundled with the asyncstorage module, or B: you explicitly alias 'localstorage' (in webpack.config.js) to the one bundled with asyncstorage. 

The reason I found myself on this thread was that A and B were both false for me, and my builds were failing. Now everything is smooth and groovy again.

Hope this helps.

**Comment by thgreasi** [comment]
Any chance you can check if #415 fixes this?

**Comment by thgreasi** [comment]
Just opened #417 that directs webpack to use the dist file of the repo.
This should remove the need of aliasing the module in your webpack configuration.
Tested with webpack v1.11 on the how-to-repo [MattKunze/localforage-webpack](https://github.com/MattKunze/localforage-webpack).
Any feedback will be much appreciated.

**Comment by tofumatt** [comment]
#417 is merged so this is closed 😄
