### ISSUE TITLE
Private Mode

### ISSUE THREAD

**Issue by ianaya89** [mozilla/localForage#302]
Hi, I want to implement localForage in a web application I want to know if the library works ok when safari or firefox are in private mode. 

Thanks.

**Comment by tofumatt** [comment]
Private browsing won't work; closing.

**Comment by linnett** [comment]
@tofumatt by "Private browsing won't work", do you mean this is a bug with Safari and there's nothing we can do to get around it?

**Comment by tofumatt** [comment]
I believe it’s still a bug with many browsers when using Private Browsing
mode—storage won’t work as expected.
