### ISSUE TITLE
Publish new release with the serializer refactoring

### ISSUE THREAD

**Issue by thgreasi** [mozilla/localForage#334]
@tofumatt Can you publish a new release (and bower etc) with 62b14837524eee39c446915b237573924092fe8b of #329?
I'm implementing a sessionStorage custom driver (aka Ctrl+H) as per #2 and this can be useful.

**Comment by tofumatt** [comment]
Sure thing, should be ready in about 15 minutes.

**Comment by tofumatt** [comment]
29f373e4fb8fa854a984b4e2e755212206beac0a and [pushed to npm](https://www.npmjs.com/package/localforage)

**Comment by thgreasi** [comment]
ty :)
