### ISSUE TITLE
Safari iOS7 Error - nopromises build v1.1.6

### ISSUE THREAD

**Issue by basiclines** [mozilla/localForage#337]
I got some errors running the ´nopromises´ build in iOS7.
With the normal build it works perfectly.

[Error] TypeError: 'undefined' is not a constructor (evaluating 'new e') 	setDriver 
[Error] TypeError: 'undefined' is not an object (evaluating 'localforage.getItem')

Just to let you know because i don't believe this is a critical issue :D

**Comment by tofumatt** [comment]
Does Safari on iOS 7 support ES6 Promises natively? If not I would expect
errors.

-tofumatt

**Comment by basiclines** [comment]
Nope is not supported you're right :D
