### ISSUE TITLE
Distribution bug: not resolving promises due to promises/asap

### ISSUE THREAD

**Issue by zdennis** [mozilla/localForage#338]
There's a conditional in the distribution build (part of the "promises/asap" section) that may be a bug. 

https://github.com/mozilla/localForage/blob/29f373e4fb8fa854a984b4e2e755212206beac0a/dist/localforage.js#L212-L219

It's the conditional part that worries me:

```
if (length === 1) {
  // If length is 1, that means that we need to schedule an async flush.
  // If additional callbacks are queued before the queue is flushed, they
  // will be processed by this flush that we are scheduling.
  scheduleFlush();
}
```

I've been unable to track down where the comment or the code originate. It seems intentional, but I can't wrap my head around why it would be checking `length === 1`. 

We have a Phonegap/Cordova app that uses localForage and all is fine until we use the FacebookConnectPlugin to authenticate. 

The first time upon authenticating, when the iOS app gets re-launched (on iOS 7.x), several items are in the queue (which were waiting to be processed until after FB authentication occurs). Because of this, the `length === 1` check fails, and none of the promises get resolved. However, if we remove the conditional then everything works perfectly. 

I'm not sure if this is indeed a bug although it feels like we've hit a corner case that is exposing one. Should the conditional should simply be `if(length > 0)`?

**Comment by tofumatt** [comment]
Hmm, I think you're right that this would be fine as length > 0. But this
is not a localForage bug directly. Can you file upstream and mention this
issue in the bug? I'll leave this open for now so people at least know
about the case.

-tofumatt

**Comment by zdennis** [comment]
@tofumatt, do you know what the upstream project is for `promise/asap`? I have dug through several repositories that define asap functionality but none of the code so far looks like it matches.

**Comment by tofumatt** [comment]
Off the top of my head I thought the promises polyfill used RSVP.js, but I honestly forget.

If that’s not it I’ll have to dig some more later :-)

**Comment by zdennis** [comment]
Thanks @tofumatt, it looks like it's the right place. I have opened an issue there.

**Comment by stefanpenner** [comment]
Which version of IOS? iOS is unfortunately known to sometimes drop pending setTimeouts in some states. It is extremely broken that this happens. I have not encountered it beyond ios6, but this does not mean it is not possible.

**Comment by thgreasi** [comment]
@zdennis can this be closed now?
Any suggestions/feedback?

**Comment by tofumatt** [comment]
I'll close this for now, but I'd love to know what the solution to your issue was and what we can do to prevent other users running into it.

If you're still having problems feel free to file more issues or re-open this as appropriate.

**Comment by zdennis** [comment]
@thgreasi / @tofumatt, we ended up patching the conditional locally IIRC, but it's been a while since I've been on that project. Will re-open if I experience it again on any others. Thanks!
