### ISSUE TITLE
localforage.createInstance: cannot create several instances with the same name (=db name)

### ISSUE THREAD

**Issue by jlchereau** [mozilla/localForage#342]
```js
var table1 = localforage.createInstance({name: 'db', storeName: 'store1' });
var table2 = localforage.createInstance({name: 'db', storeName: 'store2' });
//Do something with table1 and table2
```
This fails on Windows 8.1 + Chrome 40 (with latest updates as of 04/02/2015).
The same with different db names ('db1' and 'db2') works but you then have one IndexedDB database per table.

![image](https://cloud.githubusercontent.com/assets/2556751/6039038/96075890-ac5a-11e4-8b8d-34a8faa425d1.png)

**Comment by RobYed** [comment]
I can confirm, that createInstance with the IndexedDB driver currently doesn't create multiple instances with the same `name`. Whereas multiple instances with different `name` work. With the WebSQL driver this is not a problem at all. Same `name` but different `storeName` works well.

The feature itself is awesome! It's exactly what I needed in my app project :)

Tested with localforage version 1.2.2 on 
- Win8.1 + Chrome 43 canary
- Ubuntu 14.10 + Chrome 41
- Ubuntu 14.10 + Firefox 36 (IndexedDB driver)

**Comment by perlun** [comment]
This is indeed a bug in `localForage`. See the referenced PR (#342).

**Comment by sebweaver** [comment]
I've created the PR https://github.com/mozilla/localForage/pull/452 with a proposed implementation for fixing this issue. I hope it could help.
