### ISSUE TITLE
getItem() for unset item promise resolving as undefined

### ISSUE THREAD

**Issue by ericeslinger** [mozilla/localForage#343]
The localForage documentation indicates that something like:

    localForage.getItem('foo').then(function(data) {
      console.log(data);
    });

should show data as `null`, if there's no key named 'foo' in the localForage storage systems. I'm getting `undefined` instead of `null`. I don't particularly mind one way or the other, but I do like to know what to expect. 

I should note that this may be an angular-localForage thing, as I'm actually using that wrapper.

**Comment by tofumatt** [comment]
That is definitely unexpected, but localForage has tests to ensure it
returns null. What browser are you using?

Off the top of my head I'd say it's the wrapper just because we test for
this.

-tofumatt

**Comment by ericeslinger** [comment]
Hmm, yes - I changed the $localForage to localforage in my code (using the regular library instead of the angular-localForage wrapper), and the return changed from undefined to null, as expected.

I'll go ahead and close this, and open a ticket on the other project. And also I'll take a moment to grumble about javascript having both undefined and null.
