### ISSUE TITLE
localforage doesn't load in node

### ISSUE THREAD

**Issue by jbuck** [mozilla/localForage#345]
Test case: `require("localforage");`

This will error out with:

```
/Users/jbuck/Documents/Github/localForage/dist/localforage.js:236
}).call(window);
        ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/jbuck/Documents/Github/localForage/dist/localforage.js:236:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jbuck/Documents/Github/localForage/test.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

This is because `window` does not exist in the nodejs global environment. The line to change is at https://github.com/mozilla/localForage/blob/528025b9c90ef4a66b1c0e373033cc3131ecf656/src/localforage.js#L420

I'm not sure if making localForage work in nodejs is required, but I think it'd be nice to not have it crash within node right off the bat.

**Comment by fwenzel** [comment]
+1 on the "don't explode".

That said, it will be interesting to answer what it *should* do. Node does not ship with indexeddb does it? In that case I figure it would at least need to ship with one meaningful adapter out of the box that throwing data at would make sense?

**Comment by psalaets** [comment]
Not sure how up-to-date the contrib guide is but see https://github.com/mozilla/localForage/blob/master/CONTRIBUTING.md#features-localforage-will-reject

fwiw localforage works with browserify

**Comment by tofumatt** [comment]
Yeah, if someone can commit something that makes it work in node with little effort I guess that's fine, but right now I don't even see the use-case in node; all of the default drivers are browser-specific and localForage is aimed at browsers :smile:

**Comment by Skeen** [comment]
#57 seems related to this.

Having node support makes sense if you want to utilize the same code on both client and server end.

I guess there could be a myriad of reasons to do this; among others:

* Enabling rapid prototyping and code reuse, by (temporarily) using a sub-optimal storage scheme.
    * Eventually one could port the code to use redis or another backend system.
* Testing sub-modules of a webpage with node.
    * There can be plenty of reasons for not testing within a headless browser.
