### ISSUE TITLE
Force indexedDb in IE11?

### ISSUE THREAD

**Issue by joacim-boive** [mozilla/localForage#355]
IE11 reverts to localStorage - I'm guessing because that it has some limitations in regards to indexdDb(?).

However, I need to store more then the allotted quota in IE11 and aren't doing anything fancy with indexdDb - so I would like to override this fallback. 

If possible?

Thanks!

/J

**Comment by tofumatt** [comment]
We use IndexedDB in IE 10, I think. This could be a bug, I would think IE 11 should use IndexedDB. We might have to check what our checks for IndexedDB are.

**Comment by joacim-boive** [comment]
I caught it... It's reverting back to localStorage when IE is running in "Private Mode".
Running in regular mode, it uses indexedDb as it should.

Sorry about that. =)

/J

**Comment by tofumatt** [comment]
Ah, no worries. Yeah, private mode in a lot of browsers really messes with localForage.

I’m thinking it might be a good idea to write up a wiki article detailing the issues with private browsing mode in various browsers.
