### ISSUE TITLE
'localforage.nopromises.js' still uses promises

### ISSUE THREAD

**Issue by AshleyScirra** [mozilla/localForage#368]
Open localforage.nopromises.js and search for 'new Promise'. There are still lots of references there. So it crashes on startup in browsers like IE11 that do not support promises. This seems to defeat the point of a 'no promises' version of localforage, which is nice to have if you want to easily keep backwards compatibility with old browsers using the callback system without having to introduce polyfills for other features.

**Comment by AshleyScirra** [comment]
Oh right, I got this backwards, the promises version comes with a polyfill and the no-promises version skips the polyfill. Still, maybe it would be nice to have a version that doesn't need promises at all (not even a polyfill) and rely on callbacks only?

**Comment by tofumatt** [comment]
Sorry, but localForage relies heavily on promises and won't ship with a callback-only API. If anything I would want to move toward a Promises-only API ;-)

(I don't think there are any versions of any browsers that localForage supports that don't work with at least the polyfill anyway.)

**Comment by fmorel90** [comment]
Can it be made clearer that .nopromises uses Promises but doesn't include the polyfill? It took me a while to realize as well.

**Comment by tofumatt** [comment]
Yes, that would be useful. Filed #369.

**Comment by Triplecorpse** [comment]
Which version has promise-free api?

**Comment by tofumatt** [comment]
> Which version has promise-free api?

There is no version of localForage that does not support Promises, but you can still use callbacks.
