### ISSUE TITLE
Bug 701634 that blocks IndexedDB working in Web Workers in Firefox is fixed so localForage should work already?

### ISSUE THREAD

**Issue by sole** [mozilla/localForage#370]
https://bugzilla.mozilla.org/show_bug.cgi?id=701634 is RESOLVED FIXED but the README says localForage still doesn't support it

**Comment by tofumatt** [comment]
I don't think it's the only issue with web worker support, but without it fixed it was totally blocked. I know @dougt had a patch for this but I'm still finding time for it.

See #362.
