### ISSUE TITLE
SQLError in Safari IOS 8.3

### ISSUE THREAD

**Issue by JosephClay** [mozilla/localForage#375]
When using localforage to get a key that's not present, I'm getting an error:
```
{ code: 5, message: "could not prepare statement (1 not authorized)" }
```
instead of `null`.

Sample code:
```
var lf = require('localforage');
lf.getItem('not-there').catch(function(e) { console.log(e); });
```

So far, I've only been able to reproduce this using a browserify build on IOS 8.3.

I'm working on a quick-and-dirty test repo to show the error.

---
edit: 
Here's the test repo: [localforage-sql-err](https://github.com/JosephClay/localforage-sql-err)

**Comment by tofumatt** [comment]
I just ran this on the iOS Simulator running 8.3 and didn't get an error using the test repo.

Can you confirm it still happens? Do I need to be running it on a device rather than on the simulator?

**Comment by JosephClay** [comment]
Sorry @tofumatt , looks like this problem is a private browsing issue. I'll delete my test repo.

**Comment by tofumatt** [comment]
Ah, no worries. Yeah, private browsing really messes with the storage libraries. If we could detect that and display a console.error message about it that might be great ^_^


- tofumatt

**Comment by fbender** [comment]
`localStorage` methods throw in private browsing mode in Safari. Can we leverage that?

**Comment by tofumatt** [comment]
I think yes.




It would be useful to at least warn developers in the console! I think outputting a warning that says "localForage does not function (well) in private browsing modes" would be great, and we could possibly leverage localStorage throwing an error as our clue that we're in private browsing mode.




Good tip!



- tofumatt

**Comment by tofumatt** [comment]
#555 is addressing this; possible fallback to memory.js would include a console warning.
