### ISSUE TITLE
Question: Is there a way to force non async for a getItem

### ISSUE THREAD

**Issue by gsaqui** [mozilla/localForage#379]
Hi,

Occasionally I want to block while I get something from local storage.  I would prefer to use localforage for this as it's being used throughout the codebase.  Is this possible?

Thanks

**Comment by tofumatt** [comment]
Sorry but no; the APIs we use on the back ends are non-blocking so we have to rely on callbacks and promises.

Writing with promises gives you a code path that looks very similar to blocking calls. If you wanted to send a code sample I could suggest how to integrate them in.

**Comment by gsaqui** [comment]
Hi Matt,

Thanks for the offer - I was just being lazy and was hoping not have to
rewrite the current blocking code.

Thanks for the quick response.

Cheers,
Glenn
