### ISSUE TITLE
Publish v1.2.3 to npm

### ISSUE THREAD

**Issue by enoex** [mozilla/localForage#389]
Hello, I was trying to install the latest version from npm but It seems version 1.2.3 isn't on npm (latest version in NPM is 1.2.2: https://www.npmjs.com/package/localforage ).

**Comment by tofumatt** [comment]
Oops! Sorry about that! It's been published.

Thanks for reporting the issue :smile:

**Comment by enoex** [comment]
Woot, thanks for the fast response!
