### ISSUE TITLE
API to get the maximum size possible (in bytes/characters)

### ISSUE THREAD

**Issue by iShafayet** [mozilla/localForage#392]
It would be really helpful for applications with large offline dataset if they could invoke a simple api like `localForage.getMaximumPossibleSize()` and/or `localForage.getMaximumPossibleSafeSize()`

Where `localForage.getMaximumPossibleSize()` would return the maximum possible size of data that the application can store. This should include any hardcoded restrictions that the particular browser imposes. But should not include the limits which require user's confirmation to revoke.

`localForage.getMaximumPossibleSafeSize()` should return the maximum possible size of data that the application can store *without* prompting the user.

Best Regards
Shafayet

**Comment by SunboX** [comment]
+ one more `localForage.getRemainingSize()` (or `localForage.getAvailableSize()`)

**Comment by thgreasi** [comment]
I don't think that broewsers will expose the remaining/available storage.
This seems a privacy issue to me.
Other solutions use browser sniffing with known default sizes and estimate
the current usage using JSON.serialize for the stored items (multiplied
with an empirical factor).

**Comment by SunboX** [comment]
Jep, I didn't tell that it would be easy or would work at all. :smirk: Maybe Browsers have to expose more API's first. :cry: 

The point is, you as a developer, you know if you can wipe some **cache data** before trying to store **important data**. But by now there's no way to get this information, just "fire and forget". That's sad.

Some practical example. I'm implementing a SOAP SDK by now. We are doing some request/response caching and also storing important tokens for the SDK to work at all. Now there might be the case that I'm trying to store a token, but the storage is filled up with cached responses (that can be deleted).

**Comment by tofumatt** [comment]
Unfortunately, browsers don't expose the remaining storage available as an API that I know of. Additionally, IndexedDB in theory can store as much data as you'd like (though you might get a prompt first).

Browsers are lacking the APIs to implement this and I don't know of a good cross-browser solution that we can look to in the next year even.

I'm going to close this for now, but if things change in the future feel free to open a new issue or reopen this.

**Comment by thgreasi** [comment]
The [StorageManager API `estimate()` method](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate) might be ideal for this. Currently supported in Chrome 55 and FF51.

**Comment by xgqfrms** [comment]
https://stackoverflow.com/questions/45184719/localforage-storage-capacity
https://www.html5rocks.com/en/tutorials/offline/quota-research/
