### ISSUE TITLE
The "mozilla 5" thing on top is confusing to people!

### ISSUE THREAD

**Issue by sole** [mozilla/localForage#394]
I suggest we move it to the bottom of the column

**Comment by tofumatt** [comment]
To people or just one person? If it doesn’t make sense I’m happy to just remove it; it’s cute but it’s just visual clutter.


- tofumatt

**Comment by sole** [comment]
It was confusing for Monique, and for me too when I look at it. It doesn't make any sense on the top. That's where we expect a *title* (localForage in this case) :-)
