### ISSUE TITLE
How do I generate the documentation?

### ISSUE THREAD

**Issue by sole** [mozilla/localForage#395]
We want to contribute but it is not clear how to go from index.md to the output site that we see :-P

**Comment by tofumatt** [comment]
Totally true. I'll add this to the docs right now.

**Comment by tofumatt** [comment]
Oh, right, you need to install a bunch of Ruby garbage and I don't even have Ruby set up on my new Mac properly yet. I'll get to this _soon_ but not right now.

Related: #192

**Comment by sole** [comment]
Says something... ;-)

OK :)
