### ISSUE TITLE
Callback fires too early using IndexedDB

### ISSUE THREAD

**Issue by SunboX** [mozilla/localForage#396]
Running this sample in Firefox Developer Edition 40.0a2 (2015-06-29)

```html
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
    <title>Test</title>
    <script src="https://raw.githubusercontent.com/mozilla/localForage/master/dist/localforage.js"></script>
</head>
<body>

    <script>

	localforage.setItem('foo', 'bar', function (err, obj) {
	
		// Prevent endless re-loading
		if (document.cookie !== 'didLoad') {
			document.cookie = 'didLoad; path=/';
			
			// re-load
			//
			// Will throw:
			// An IndexedDB transaction that was not yet complete has been aborted due to page navigation.
			document.location.reload(true);
		}
	});
	
    </script>

</body>
</html>
```

will warn with

```text
An IndexedDB transaction that was not yet complete has been aborted due to page navigation.  localforage.js:1071:0
An IndexedDB transaction that was not yet complete has been aborted due to page navigation.  localforage.js:1076:0
An IndexedDB transaction that was not yet complete has been aborted due to page navigation.  localforage.js:1276:0
```

## Expected result
Callback fires when all data is stored, so no warning if you navigate away.

**Comment by thgreasi** [comment]
I think that in indexeddb the transactions get auto committed at some point
after an idle time and there is no manual ` transaction.compete();`.
Is anyone aware of an event firing right after the transaction gets
committed?

**Comment by SunboX** [comment]
I dont know if you have to wait for the `req.onsuccess` her:
https://github.com/mozilla/localForage/blob/master/src/drivers/indexeddb.js#L324

MDN:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Adding_data_to_the_database

**Comment by SunboX** [comment]
Here is a related stackoverflow question:
http://stackoverflow.com/questions/29242346/an-indexeddb-transaction-that-was-not-yet-complete-has-been-aborted-due-to-page

**Comment by SunboX** [comment]
Seems to be a Firefox Bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1147942

**Comment by tofumatt** [comment]
From reading the bug, everything is actually okay but the warning was displaying regardless of a successful write?

ie. this was a Firefox bug, doesn't happen elsewhere, and should be fixed in Nightly?

**Comment by SunboX** [comment]
Yeah, just updated to Firefox Developer Edition 41.0a2 (2015-07-06) and all is fine now. No more warnings. Seems fixed to me. :smile:

**Comment by tofumatt** [comment]
Yay! Thanks for the update.

- tofumatt
