### ISSUE TITLE
bower version problems

### ISSUE THREAD

**Issue by badpenguin** [mozilla/localForage#397]
i used "bower install localForage", then i got the file from the DIST directory and promises does not work with it, expecially $q.all() does not allow me to syncronize tasks.

i went here on GIT and got the same file from the DIST directory downloading the raw version
and now it works.

The difference is 2K from the 2 files.

Maybe the bower version got downloaded from a different repository?

**Comment by tofumatt** [comment]
bower should get stuff from GitHub, but I haven't pushed a new release since May 14.

I just [pushed a new version](https://github.com/mozilla/localForage/releases/tag/1.2.4). Should be fixed now.
