### ISSUE TITLE
Refactor: move serializer variable into dbInfo

### ISSUE THREAD

**Issue by thgreasi** [mozilla/localForage#398]
Such a change would allow us to make custom drivers DRYer.
Simple drivers could greatly reduce their code and file size by overriding only the different methods and reusing the rest ones. The problem currently is that the serializer is referenced by the closures of the  driver methods. Attaching it to dbInfo would be great.

For example, sessionStorage and CordovaSQLitePlugin drivers would just need to override the _initStorage methods and reuse localStorageWrapper and websqldriver respectively.

Making localforage drivers architecture more object oriented (maybe es6 class based) would be an other step forward.

No PR yet, just discussing. Waiting for other major PRs to merge.

**Comment by tofumatt** [comment]
This is an awesome idea.




Agreed, we'll merge some other stuff before tackling it but this is a great idea.



- tofumatt
