### ISSUE TITLE
Add externs file for Google Closure Compiler

### ISSUE THREAD

**Issue by SunboX** [mozilla/localForage#399]
Pleas add a `externs` file for use with the Google Closure Compiler:
https://github.com/google/closure-compiler/tree/master/contrib/externs

**Comment by tofumatt** [comment]
Not sure what this is or where the documentation is... or why we should do it. Can you elaborate please? Thanks :smile:

**Comment by SunboX** [comment]
Google Closure Compiler is a *minifier* and a *compiler* for JavaScript. If you run it in `ADVANCED_OPTIMIZATIONS` mode, it will re-organize your code, simplify it and tries to remove unused code as much as possible.
But this has some side effects ... if your code does rely on **external code**, like `localforage.getItem()`, the closure compiler will try to re-name it or remove it at all, because it doesn't *know* what this code is for.

To avoid this, you can feed the compiler with so called *externs* files. Externs are *pseudo* JavaScript files with some annotations, telling the compiler what to keep.

So my compiler config looks something like this:
```js
'closure-compiler': {
    main: {
        closurePath: 'lib/closure-compiler',
        js: [
            '<%= distFolder %>/<%= pkg.name %>.js',
            'closure-compiler-exports.js'
        ],
        jsOutputFile: '<%= distFolder %>/<%= pkg.name %>.compiled.js',
        options: {
            compilation_level: 'ADVANCED_OPTIMIZATIONS',
            language_in: 'ECMASCRIPT5_STRICT',
            externs: [
                'lib/closure-compiler-externs/jquery-1.9.js',
                'lib/closure-compiler-externs/jquery.soap.js',
                'lib/closure-compiler-externs/xml2json.js',
                'lib/closure-compiler-externs/localForage.js' // <--- here it is
            ]
        }
    }
}
```

And the **externs file for Google Closure Compiler**, what this issue is about, will look like this:
```js
/**
 * @fileoverview Externs for localForage
 *
 * @see https://github.com/mozilla/localForage
 * @externs
 */
 
/** @typedef {function(...)} */
var localForageCallback;

 /** @typedef {{
    description: (?string|undefined),
    driver @param (Array<*>|undefined)
    name: (?string|undefined),
    size: (?int|undefined),
    storeName: (?string|undefined),
    version: (?*|undefined)
}} */
var localForageConfig;

/**
 * @constructor
 * @param {localForageConfig=} options
 * @return {!localforage}
 */
function localforage(options) {}

/**
 * @param {localForageConfig} options
 */
localforage.prototype.config = function(options) {};

/**
 * @param {string} key
 * @param {*} value
 * @param {localForageCallback} callback
 */
localforage.prototype.setItem = function(key, value, callback) {};

/**
 * @param {string} key
 * @param {localForageCallback} callback
 */
localforage.prototype.getItem = function(key, callback) {};

/**
 * @param {string} key
 * @param {localForageCallback} callback
 */
localforage.prototype.removeItem = function(key, callback) {};

/**
 * @param {localForageCallback} callback
 */
localforage.prototype.clear = function(callback) {};

/**
 * @param {int} n
 * @param {localForageCallback} callback
 */
localforage.prototype.key = function(n, callback) {};

/**
 * @param {localForageCallback} callback
 */
localforage.prototype.keys = function(callback) {};

/**
 * @param {localForageCallback} callback
 */
localforage.prototype.length = function(callback) {};
```

This file works for me. I don't know if it is complete. :smirk:

**Comment by SunboX** [comment]
And I don't know where to put such such resource. Think this may be helpful to someone other than me. Can you put this into some `support` folder?

**Comment by thgreasi** [comment]
It seems that in most cases people create a separate repo and add it in the [closure-compiler/wiki](https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries).
That's the case for Backbone, Underscore, React and Firebase.
It's a pity thought that there is no central repo like what people are doing for [Typescript definition files](https://github.com/borisyankov/DefinitelyTyped).

**Comment by tofumatt** [comment]
I’m not a frequent user of Closure Compiler nor knowledgable on it, so a pull request will be much helpful here. If I should create a Mozilla repo for this (localforage-closure-exports) I can do that.


Otherwise I won’t likely get to this anytime soon.


- tofumatt

**Comment by tofumatt** [comment]
Closing due to lack of progress on this one.
