### ISSUE TITLE
localStorage driver iterate function fetches items which are not owned by localforage db

### ISSUE THREAD

**Issue by rasikas** [mozilla/localForage#407]
I found this issue when localforage is used in an environment where browser is IE and when localforage is using localStorage driver.

I think issue is localforage assumes entire localstorage is owned by itself which is not the case in certain applications, some other javascripts and apps can use same localstorage to store their values. So localforage must not assume and work as its own entire localstorage and its data. 

Check the following iterate method

https://github.com/mozilla/localForage/blob/master/src/drivers/localstorage.js#L102
~~~js
    function iterate(iterator, callback) {
        var self = this;

        var promise = self.ready().then(function() {
            var keyPrefix = self._dbInfo.keyPrefix;
            var keyPrefixLength = keyPrefix.length;
            var length = localStorage.length;

            for (var i = 0; i < length; i++) {
                var key = localStorage.key(i);
                var value = localStorage.getItem(key);

                // If a result was found, parse it from the serialized
                // string into a JS object. If result isn't truthy, the
                // key is likely undefined and we'll pass it straight
                // to the iterator.
                if (value) {
                    value = serializer.deserialize(value);
                }

                value = iterator(value, key.substring(keyPrefixLength), i + 1);

                if (value !== void(0)) {
                    return value;
                }
            }
        });

        executeCallback(promise, callback);
        return promise;
    }
~~~
After `var key = localStorage.key(i);` it should check whether key is related to its data before fetching the value. This check has been done in other methods. It should not deserialize the item if it is not stored by localforage (simply someone else' data) which could throw exceptions and unpredictable behaviours, Moreover caller of this library expect to get data what it stored using localforage, not all the data stored in browser localstorage.

**Comment by fatfisz** [comment]
This surprised me too, shouldn't `iterate` and `keys` be consistent in which keys do they ignore?

**Comment by tofumatt** [comment]
Yes, this looks like a bug, I thought it had already been reported but I can't find it (at least on my phone).

Thanks for finding it!

**Comment by af7** [comment]
Hello, this is a bug that causes errors in my case, because I use *two* dbs inside localStorage.

This is why I added this code...

````
if (!(key.indexOf(keyPrefix) === 0)) continue;
````

...between these lines here:

````
var key = localStorage.key(i);
var value = localStorage.getItem(key);
````
https://github.com/mozilla/localForage/blob/master/src/drivers/localstorage.js#L112-L113

Could you *please* add these to MASTER so that localForage behaves as expected?

I really need to just add the npm package to my project and not have to compile the source files (so that I get this issue fixed).

Thanks!

**Comment by tofumatt** [comment]
Sure thing. I've responded to the pull request, would you be able to add a test to the PR as well? If not I'll try to add my own but it won't be for a few hours or maybe tomorrow. Thanks!



- tofumatt

**Comment by af7** [comment]
Hello Matthew,

glad to be of help, I see that you replied to the PR and that you will add the test in a few hours. 

Thank you!
