### ISSUE TITLE
When no drivers are availabel agrees with modernizr on storage drivers support fails with modernizr v3.0.0-alpha.3

### ISSUE THREAD

**Issue by remkoboschker** [mozilla/localForage#409]
When No Drivers Are Available agrees with Modernizr on storage drivers support:
Error: expected false to equal true
 at http://localhost:9999/bower_components/expect/index.js:102
 at http://localhost:9999/bower_components/expect/index.js:219
 at http://localhost:9999/bower_components/expect/index.js:69
 at http://localhost:9999/test/test.nodriver.js:23
 at callFn (http://localhost:9999/bower_components/mocha/mocha.js:4338)
 at http://localhost:9999/bower_components/mocha/mocha.js:4331
 at http://localhost:9999/bower_components/mocha/mocha.js:4728
 at http://localhost:9999/bower_components/mocha/mocha.js:4819
 at next (http://localhost:9999/bower_components/mocha/mocha.js:4653)
 at http://localhost:9999/bower_components/mocha/mocha.js:4663
 at next (http://localhost:9999/bower_components/mocha/mocha.js:4601)
 at http://localhost:9999/bower_components/mocha/mocha.js:4630
 at timeslice (http://localhost:9999/bower_components/mocha/mocha.js:5761)

**Comment by tofumatt** [comment]
Sorry, but I don't quite understand the issue. Could you show me the code you're trying to run that's failing?



- tofumatt

**Comment by remkoboschker** [comment]
Hi, I updated to modernizr 3 to check for service worker availability. This caused another test to fail. We have used another test to check for it without updating modernizr. https://github.com/mozilla/localForage/pull/406

**Comment by tofumatt** [comment]
Cool, thanks for the update.
