### ISSUE TITLE
End users lose data when upgrading to a browser with IndexedDB

### ISSUE THREAD

**Issue by PikadudeNo1** [mozilla/localForage#41]
AFAIK, there is no storage abstraction library that gracefully deals with IndexedDB suddenly being available when it wasn't before; thus, end users of an app that use such a library find all their data "lost" when they update to a browser version that has IndexedDB. Fixing this in localForage would not only be great for end users, it would help set this library apart from the competition.

**Comment by tofumatt** [comment]
Most browsers in question have moved to IndexedDB and this seems to be something developers will need to handle themselves. Closing for now, but a PR to fix this would still be welcome.
