### ISSUE TITLE
v1.2.6, Browserify and Ampersand-localforage 

### ISSUE THREAD

**Issue by rejas** [mozilla/localForage#413]
Since this weekend our build system chokes on the updated version of localforage. Using Browserify and ampersand-localforage we get this error:

13:31:18 [13:31:30] Browserify Error { [SyntaxError: Unexpected token (144:10) while parsing /home/.../node_modules/ampersand-sync-localforage/node_modules/localforage/src/localforage.js while parsing file: /home/.../node_modules/ampersand-sync-localforage/node_modules/localforage/src/localforage.js]

The version before just worked fine with the current ampersand-localforage/browserify :-(  Any hints on what we can change maybe on our side?

**Comment by tofumatt** [comment]
No, this is my fault, sorry :cry: 

When we did the refactor into es6 we removed support for including `src/localforage.js` and require people to include the fully built version in `dist`. I've never officially supported including the source files but I think it's always worked until now and a lot of people have been doing it--but it causes us headaches :smile: 

I should have marked this as a version bump to 1.3 and didn't. I'll push 1.2.7 soon and it should continue working. Then I'll push 1.3, which won't work as you've been using but should work with the `dist/` version.

Sorry about all this. Should be fixed soon.

**Comment by thgreasi** [comment]
Me sorry too :(

**Comment by tofumatt** [comment]
Uploaded a new release to GitHub and npm. This should be fixed now, but there will be a new release later today: 1.3 that **will not support loading `src/localforage`** and will only work with the `dist/localforage.js` version.

**Comment by thgreasi** [comment]
We  also have to change the "browser" field in package.json to target the
dist file as well.

On Mon, Aug 3, 2015, 14:57 Matthew Riley MacPherson <
notifications@github.com> wrote:

> No, this is my fault, sorry [image: :cry:]
>
> When we did the refactor into es6 we removed support for including
> src/localforage.js and require people to include the fully built version
> in dist. I've never officially supported including the source files but I
> think it's always worked until now and a lot of people have been doing
> it--but it causes us headaches [image: :smile:]
>
> I should have marked this as a version bump to 1.3 and didn't. I'll push
> 1.2.7 soon and it should continue working. Then I'll push 1.3, which won't
> work as you've been using but should work with the dist/ version.
>
> Sorry about all this. Should be fixed soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/413#issuecomment-127209459>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment]
Good to know, I’ll do that in the 1.3 version. I’ll release that at some point today :-)


- tofumatt

**Comment by rejas** [comment]
Since ampersand-sync-localforage uses 
    "localforage": "^1.0.0",

will it also try to get v1.3 then and break again?

**Comment by tofumatt** [comment]
Hmm, it might.




Should we just declare this as version 2.0 given it’s a big refactor? I’m okay with that.


- tofumatt

**Comment by rejas** [comment]
Sounds like a good idea since other users of ampersand-sync-localforage might be surprised too :-)

**Comment by tofumatt** [comment]
Yeah. Means I might delay the release a few days and go through anything else I might want to change in a big version bump. :-)


- tofumatt

**Comment by thgreasi** [comment]
Just pointing to the dist file in package.json should be enough I think.

On Mon, Aug 3, 2015, 15:15 Veeck <notifications@github.com> wrote:

> Sounds like a good idea since other users of ampersand-sync-localforage
> might be surprised too :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/413#issuecomment-127215417>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by rejas** [comment]
Maybe I could try to fix it myself and open a pull request to the original ampersand-sync-localforage, but who knows when it will get merged :-)
