### ISSUE TITLE
self._initStorage is not a function  

### ISSUE THREAD

**Issue by thejourneydude** [mozilla/localForage#416]
I'm running localForage on my app. I installed the app via bower and have access to it via the console. When I type in 

    localforage.setItem('key', 'value', function(err, value) { return value; });

I receive the following error.

    self._initStorage is not a function

However, if I type in `localforage` in the console I receive

    LocalForage {_config: Object, _driverSet: Promise, _ready: null, _dbInfo: null}

What's wrong and how do I fix this?

**Comment by tofumatt** [comment]
Hi there! What is the reason you closed the issue? If there's a problem with the docs that led to this bug, please let me know!



- tofumatt

**Comment by thejourneydude** [comment]
It was an error on my part. It’s fixed now. Sorry for the trouble.

**Comment by tofumatt** [comment]
No worries. Don't feel shy about filing other issues, and thanks for using the library! :-)



- tofumatt

**Comment by zcsongor** [comment]
@thejourneydude I have the same problem, could you help me out?

**Comment by chriswininger** [comment]
What was the error? I see the same thing, even in the examples straight from the bower github. What am I missing here?
