### ISSUE TITLE
Add documentation for supports() and driver() APIs

### ISSUE THREAD

**Issue by tofumatt** [mozilla/localForage#423]
As mentioned in #412, we have a `supports()` and a `driver()` method but they aren't documented. Since @af7 has expressed a use-case for it we should document it for all! :smile:

**Comment by af7** [comment]
Thx, you may also add the `driver()` method, as this is what I will be using in my case.

I will be checking for `null` and if yes then test if our own driver can be supported on the specific hardware and load it instead.

**Comment by af7** [comment]
Not sure if this needs a different ticket, I also use the `createInstance` in order to create 2 different localforage databases (thus I had the bug with `iterate`).

So, maybe you would like to document `createInstance` too (it is not documented).

**Comment by tofumatt** [comment]
There’s actually an issue open for that (#260), but we haven’t got around to fixing it yet. I’m guessing multiple instances are a lesser-used feature, as for many the appeal of localForage is it’s plug-and-play nature.




Still, would love to have those docs too!


- tofumatt
