### ISSUE TITLE
README uses inconsistent example (in set item)

### ISSUE THREAD

**Issue by remy** [mozilla/localForage#426]
The following from the README:

```js
// In localStorage, we would do:
localStorage.setItem('key', JSON.stringify('value'));
alert('value');

// With localForage, we use callbacks:
localforage.setItem('key', 'value', function(err, value) { alert(value); });
```

...is quite confusing. Specifically, the `localStorage` stored value is `"value"`, yet the alerted string is *just* `value` (note - no wrapping quotes) and the the `localforage` stores `value`, but I'm now confused as to whether localforage is going to stringify...or not, or if it matters.

I think a good example (though I didn't PR this because I've not tested it myself) would be to use an object, along the lines of:

```js
// In localStorage, we would do:
var obj = { value: "hello world" };
localStorage.setItem('key', JSON.stringify(obj));
alert(obj.value);

// With localForage, we use callbacks:
localforage.setItem('key', obj, function(err, result) { alert(result.value); });
```

(This assumes localforage handles serialisation).

Thoughts?

**Comment by thgreasi** [comment]
:+1:

**Comment by tofumatt** [comment]
For what it's worth your code will work; localForage handles serialisation.

That's a great point. The example is pretty silly. :+1: from me as well; if you send that as a PR we'll happily merge it.
