### ISSUE TITLE
localforage seems not to work with webpack

### ISSUE THREAD

**Issue by magsout** [mozilla/localForage#441]
Sorry in advance if my issue is a duplicate. I read the README and initially some issues but "localForage" is not working properly with webpack.

Here my first config : https://gist.github.com/magsout/f3964beafbf31531bef3#file-index-js

If I run webpack, I have this error https://gist.github.com/magsout/f3964beafbf31531bef3#file-error-txt

I looked for issue on webpack and I found this one: https://github.com/mozilla/localForage/issues/344#issuecomment-114768603

I tried the config and it seems works correctly:

But there is nothing mentioned about it in the README https://github.com/mozilla/localForage#browserify-and-webpack

If I require `require('script!localforage')` in webpack I have this error  https://gist.github.com/magsout/d9f36a437812975fee7d

I maybe missed something in the configuration? Thank you in advance for your help.

**Comment by thgreasi** [comment]
What version of localForage do you use? Do you use npm or bower to install?

**Comment by thgreasi** [comment]
I'm afraid I forgot to also mention about using [webpack script loader](https://github.com/webpack/script-loader).
Take a look at https://github.com/thgreasi/localforage-webpack .

**Comment by magsout** [comment]
>What version of localForage do you use? Do you use npm or bower to install?

`npm` -  `"version": "1.2.10",`

**Comment by stephenrs** [comment]
I'm having the same problem. Also installed v1.2.10 via npm.

**Comment by magsout** [comment]
@thgreasi my bad, just need ton install `npm install script-loader` and it works.

Thanks

**Comment by magsout** [comment]
@stephenrs  try ton install `npm install script-loader`and add

`var localforage = require("script!localforage")` in your js file, seems to work fine

**Comment by thgreasi** [comment]
Great, it's just that with script loader you don't need the `var localforage =` part, just `require("script!localforage")`.

**Comment by stephenrs** [comment]
@magsout That worked perfectly. Thanks so much...and @thgreasi Thank you so much for the tip - I've never used the script loader before. Really great help, right when I needed it!

**Comment by thgreasi** [comment]
Should we close this now?

**Comment by magsout** [comment]
Yes thanks
