### ISSUE TITLE
Error: Refused to connect to 'blob:http

### ISSUE THREAD

**Issue by siddo420** [mozilla/localForage#445]
I am getting the following error message in Chrome

```
Refused to connect to 'blob:http%3A//192.168.1.9%3A8080/3547f91f-dd73-48a4-9bf1-233c183c22ed' because it violates the following Content Security Policy directive: "connect-src 'self' wss://192.168.1.13 https://192.168.1.13".

_createBlob.type @ localforage.js:1036
_blobAjax @ localforage.js:1034
txn.oncomplete.getBlobReq.onsuccess @ localforage.js:1087
```

JS and HTML are served from http://192.168.1.9:8080

**Comment by tofumatt** [comment]
Can you include the JS you are running that's causing the error and also your server's CSP rules? This looks like a CSP directive violation, perhaps you're trying to store or retrieve data you aren't allowed to interact with in JS.




I can see the blob was retrieved successfully as the error happens inside the onsuccess handler.



- tofumatt

**Comment by coolaj86** [comment]
I'm having the same issue with this snippet:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>LocalForage Test</title>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'self' http://conf.utahjs.com/; font-src 'self' https://fonts.googleapis.com/css/ https://fonts.gstatic.com/s/raleway/; style-src 'self' https://fonts.googleapis.com/css; child-src 'none'; object-src 'none'; img-src 'self' https://avatars.githubusercontent.com/ https://avatars.io/email/ https://avatars.io/twitter/ https://www.gravatar.com/avatar/">
    <link rel="stylesheet" href="bower_components/bootswatch-dist/css/bootstrap.css" />
  </head>
  <body>
    <script src="bower_components/localforage/dist/localforage.js"></script>
    <script src="lf-test.js"></script>
  </body>
</html>
```

```js
(function () {
  'use strict';

  var store = window.localforage.createInstance({
    name: "conf"
  });

  store.getItem('schedule').then(function (err, sched) {
    if (err) {
      console.error(err);
    }
    if (sched) {
      console.log(sched);
    }
    console.log('blah');
  });

  store.setItem('schedule', {});
}());
```

![screen shot 2015-09-12 at 4 42 53 pm](https://cloud.githubusercontent.com/assets/122831/9834192/7051bd14-596d-11e5-8f5b-aedbdbe2ec1f.png)

**Comment by coolaj86** [comment]
I don't understand the security implications of adding a blanket catchall `blob:` to `connect-src 'self' blob: https://example.com/`, so I would be very hesitant to say that doing so "fixes" the problem.

**Comment by thgreasi** [comment]
How does your lf-test.js looks like?

On Sun, Sep 13, 2015, 01:50 AJ ONeal <notifications@github.com> wrote:

> I don't understand the security implications of adding a blanket catchall
> blob: to connect-src 'self' blob: https://example.com/, so I would be
> very hesitant to say that doing so "fixes" the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/445#issuecomment-139826217>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by coolaj86** [comment]
The code I showed you is the lf-test.js

**Comment by thgreasi** [comment]
Oh, sorry, It looked confusing in my mail client :disappointed:

**Comment by tofumatt** [comment]
@coolaj86 Sadly, it may be the way around your CSP issue. localForage creates a Blob object from serialised data inside a WebSQL/localStorage database when not using IndexedDB, and retrieves the blob directly from IndexedDB otherwise.

Your CSP rules will need to allow interacting with local Blob objects. I don't think there's a way to limit this beyond "all blobs from self". I am no security expert, but I would think trusting local Blobs would be okay from a security standpoint.

If you allow the Blob from your URL (`connect-src 'self' blob: https://conf.utahjs.com/` or whatnot? I'm not sure on the syntax, sorry) does it work?

If so, I won't consider this an error; it's outside the scope of localForage. :disappointed:

**Comment by siddo420** [comment]
My browser stopped complaining ie. no error messages anymore. 

I hope it'd not create any security issues.

Thanks.

**Comment by tofumatt** [comment]
Okay then, closing this for now; don't think it's a localForage issue.

**Comment by rocco** [comment]
I had a similar issue with an ionic app on android that uses localForage. I had to set this:

    <meta http-equiv="Content-Security-Policy" content="connect-src 'self' file: data: blob: filesystem:; default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"/>

As connect-src does not use wildcard for blob: you need to set everything explicitly for it.
