### ISSUE TITLE
Expose the serializer on the localForage object/namespace

### ISSUE THREAD

**Issue by thgreasi** [mozilla/localForage#446]
This is to gather the discussion that appeared in #412 & #432 (@tofumatt, @af7 )
My two suggestions:
* `localforage.serializer` returning the actual serializer object
* `localforage.getSerializer()` returning a promise

## `localforage.serializer` returning the actual serializer object
Pros:
* use es6 static imports

Cons:
* load the serializer even in cases that it's not needed (eg: IndexedDB with unbundled RequireJS, do we even support it any more?)

This will make even more sense if we move [the IndexedDB driver's blob serialization code](https://github.com/mozilla/localForage/blob/9d2b28b5f508f2dd38e4a133ddd5ca9baaea7209/src/drivers/indexeddb.js#L17-L168) into the main serializer.

Sample implementation:
```js
// on the top of localforage.js, ouside the IIFE
import serializer from 'utils/serializer'

// near the end of localforage.js inside the IIFE
localForage.serializer = serializer;
export default localForage;
```

## `localforage.getSerializer()` returning a promise
Pros:
* We don't import anything if not really required/requested
* That's the way the drivers are currently implemented and we could refactor them to use the exposed method, instead of doing a `System.import` in their own

Cons:
* The developer will have to wait for a promise to resolve

```js
// add a method to the LocalForage class
getSerializer() {
  return System.import('./utils/serializer');
}
```

**Comment by tofumatt** [comment]
I think waiting for the promise to resolve is okay, and is very much like the rest of our other APIs. I'm for that one. I'm not sure when we would need to load a serialiser async but it does let us do that as well.



- tofumatt

**Comment by thgreasi** [comment]
+1
