### ISSUE TITLE
typescript + es6 imports can't access .config

### ISSUE THREAD

**Issue by stephenlautier** [mozilla/localForage#450]
Hi there,

Not sure if I'm missing anything or doing something wrong.

Basically I'm using this library with TypeScript and es6 style imports (along with jspm and systemjs), and the problem is I can't access the `.config` or `.createInstance`, I can access the main functionalities such as `.getItem` and `.setItem` so I'm assuming I'm only getting the `LocalForage` instance which is being exported here: https://github.com/mozilla/localForage/blob/master/src/localforage.js#L375.

My code looks something like this:

```
import * as localforage from "localforage";

describe("LocalforageSpecs", () => {

	describe("configSpecs", () => {

		it("should be defined correctly", (done) => {

			debugger;
			var store = (<any>localforage).createInstance({
				name: "da instance"
			});

			expect(store).toBeDefined();
			
			(<any>localforage).config({
				name: "testyo"
			});

			expect(localforage).toBeDefined();
			done();
		});

	});
});
```

It will be generated down to:

```
System.register(["localforage"], function(exports_1) {
    var localforage;
    return {
        setters:[
            function (_localforage) {
	            debugger;
                localforage = _localforage;
            }],
        execute: function() {
            beforeEach(JasminePromiseMatchers.install);
            afterEach(JasminePromiseMatchers.uninstall);
            describe("LocalforageSpecs", function () {
                describe("configSpecs", function () {
                    it("should be set correctly", function (done) {
                        debugger;
                        var store = localforage.createInstance({
                            name: "da instance"
                        });
                        expect(store).toBeDefined();
                        localforage.config({
                            name: "testyo"
                        });
                        expect(localforage).toBeDefined();
                        done();
                        //expect(localforage)
                    });
                });
            });
        }
    }
});
```

Is there a way I can access the `.config` or `.createInstance`? Thanks!

**Comment by stephenlautier** [comment]
After some debugging the only way I seem to access it is by doing:
```
localforage.default.config(...
```

**Comment by thgreasi** [comment]
Hmm I guess that your import is targeting the src files, right?
What results you get when you import one of the dist files?

On Tue, Sep 15, 2015, 00:15 Stephen Lautier <notifications@github.com>
wrote:

> After some debugging the only way I seem to access it is by doing:
>
> localforage.default.config(...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/450#issuecomment-140207906>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by stephenlautier** [comment]
Not entirely sure which one it was using exactly, its the default which jspm points to.
After some digging I noticed this seems to be happening due to systemjs and the way I was importing.

I was using this:
```
import * as localforage from "localforage";
```
Which causes proto's to be attached with `localforage.default`.

Instead by using `default as` when importing (as below) I believe it works correctly - I haven't tried it with localforage yet but with momentjs I had the same issue, and using the `default as` seemed to be to proper way.

```
import {default as localforage} from "localforage"
```

Cheers

**Comment by thgreasi** [comment]
`import localforage from "localforage"` should also work, (I think).

**Comment by stephenlautier** [comment]
That might work in es6 imports but I don't think it would work in TypeScript :).

AFAIK these are valid imports for TypeScript using the new imports syntax introduced in 1.5:

#### Import all
```
import * as localforage from "localforage";
```
#### Import using default
```
import {default as localforage} from "localforage"
```

#### Import single
this one syntax wise works, however @ runtime its not
```
import {localforage} from "localforage"
```
Thanks for the help though :+1:

**Comment by tofumatt** [comment]
Looks like this was resolved, should we add anything into the docs for other Typescript users?

**Comment by stephenlautier** [comment]
Sure, my PR for the definitions is still pending (https://github.com/borisyankov/DefinitelyTyped/pull/5805) after that one is merged it can be used as following:


#### Import using default
I believe this is the best approach, however sometimes in VS it was causing intellisense to not work properly.
```
import {default as localforage} from "localforage"
```

#### Import all
This is the other approach which also works (and currently this is what I'm personally using due to the issue I stated above)
```
import * as _localforage from "localforage";
var localforage = _localforage.default;
```

**Comment by tofumatt** [comment]
I'd certainly prefer the first one; second one reads like a hack (and I'm guessing a bug in Visual Studio's code parsing).

**Comment by dsebastien** [comment]
Does anyone know the current way of importing localforage w/ TypeScript?

I've tried the various suggestions above to no avail...

**Comment by dsebastien** [comment]
Actually, the documented way works with a caveat:

```
import {default as localforage} from "localforage";

localforage.clear();
localforage.setItem("mykey", "myvalue", console.log);
```

with the import as described above, WebStorm/IntelliJ seem unable to provide autocompletion. It might be that they don't support the 'default as' syntax.. I'll file an issue over there as it's only an issue within the IDE.

**Comment by dsebastien** [comment]
Just for reference, here's the link to the issue I've created over at Jetbrains: https://youtrack.jetbrains.com/issue/WEB-19765

**Comment by stephenlautier** [comment]
@dsebastien this should be the best way of doing this

```
import lf from "localforage";

lf.getItem("gen:core:auth")
	.then(x => {
		console.log("YORDLE?!", x);
	});
```
You can name `lf` as whatever you want.

Note: I don't use Webstorm, I'm using Visual Studio Code and Visual Studio but I believe it works the same on webstorm.

Hope it helps!

**Comment by dsebastien** [comment]
@stephenlautier I've just tried this but it doesn't work with my configuration. TSC does not complain but generates the following:

```
...
var localforage_1 = require("localforage");
...
localforage_1.default.setItem("key", "cool");
```

And that fails at runtime because 'default' is undefined.

I'm using TS 1.7.3 and SystemJS to load the modules. I'm guessing this might either be due to the way SystemJS loads the modules or the way TS does its transpilation (I've configured it to transpile to ES5 commonjs modules...).

I've created a PR to change the typings file even though Jetbrains will include a [fix](https://youtrack.jetbrains.com/issue/WEB-19765) in their next release. I don't think that the 'default' keyword brings anything useful anyways (it's the only export).

**Comment by stephenlautier** [comment]
I used to get that issue but not anymore. 
I'm compiling it to `es5` and `system` (not commonjs) and it works, using typescript 1.7.5.

#### src
usage
```
import lf from "localforage";

lf.setItem("test:value", "it works!");
```

#### compiled
```
localforage_1.default.setItem("test:value", "it works!");
```

**Comment by dsebastien** [comment]
Good to know, thanks.
I'll test my modifications with the system module format to make sure that it also works there. 
I know that I had to switch from system to commonjs at some point in my project due to bugs that weren't resolved yet at the time

**Comment by lovasoa** [comment]
I still get this error. When using an asynchronous module import, the typescript annotations in this package tell me I can do

```ts
(await import("localforage")).createInstance({})
```

But it fails at runtime with `TypeError:  createInstance is not a function`.

To get it to work, I have to write:

```ts
(await import("localforage")).default.createInstance({})
```

I think the provided type information is wrong
