### ISSUE TITLE
Why is localForage not working in IE11?

### ISSUE THREAD

**Issue by PJudson001** [mozilla/localForage#454]
I am simply running a simple test using localforage.setItem and localforage.getItem, it works in Chrome and Firefox but not in IE11. I am able to alert the set and get values.

I also reset IE, remove all personal settings but the code still does not work. Meaning when I run the code, the screen is blank, there are no alerts or prompt as displayed in other browsers.

Does localforage work in IE11?

**Comment by tofumatt** [comment]
Looks like you're missing the code, though it's possible we do have IE 11 bugs (though we shouldn't).

**Comment by PJudson001** [comment]
Code:

localforage.setItem('1', 'United States', function(err, value) {
    alert(value);
    localforage.getItem('1', function(err,value) {
        alert('we just read ' + value);
    });
});

**Comment by thgreasi** [comment]
@PJudson001 Does [this pen](http://codepen.io/thgreasi/pen/ojYKeE) work for you?
It works for me, on Win7 IE11.
@tofumatt How about adding such an example in the README?

**Comment by thgreasi** [comment]
Any feedback on this?

**Comment by tofumatt** [comment]
Tested in IE 11 Karma on Sauce Labs recently and tests passed. Closing this one.
