### ISSUE TITLE
Doesn't load in a web worker

### ISSUE THREAD

**Issue by nolanlawson** [mozilla/localForage#455]
I see the error `window is not defined` when I try to load `localForage` in a webworker. Should be a pretty easy fix; just need to remove references to `window` and use globals instead.

**Comment by thgreasi** [comment]
This should be fixed in master. Can you give it a try?

**Comment by thgreasi** [comment]
Was fixed by #406 if I'm not mistaken.

**Comment by nolanlawson** [comment]
cool, I'm installing localforage from npm, version 1.2.10. any chance of a publish?

**Comment by thgreasi** [comment]
I think that the next version will be 1.3 which will have a lot of changes (not in the API). I can't estimate its release.
Maybe @tofumatt has a better insight on this.

**Comment by tofumatt** [comment]
I'd like to try and release it this weekend; I've recently switched teams at Mozilla and have a bit less time for localForage during the week, but I try to spend the weekends on it.

This should change once things calm down, but for now I would *love* to have 1.3 out this weekend!

**Comment by thgreasi** [comment]
Wait!!!!!!
We also need to add `getSerializer()`!!!

**Comment by tofumatt** [comment]
Oh right!

Don't worry, I won't publish anything until I'm sure (and double check with you! 😀)

- tofumatt

**Comment by tofumatt** [comment]
Since `getSerializer()` was added and things seem good I pushed 1.3; this way we're back to publishing the version on master, yay!

This bug should be fixed now, sorry it took ages. :tired_face:
