### ISSUE TITLE
iOS 7.1.2 Safari Error

### ISSUE THREAD

**Issue by alexstanbury** [mozilla/localForage#456]
I'm loading the promises polyfilled version (localforage.js) but I am getting an error when using on this browser. The error is as follows:

TypeError: 'undefined' is not an object (evaluating 'adbinfo.db.transaction')

Any ideas?

**Comment by tofumatt** [comment]
What version of localForage are you using? Any chance you’re using Private Browsing mode? I think we fixed bugs with it but I haven’t pushed the version yet; I should do that soon.

- tofumatt

On 1 October 2015 at 16:29:58, alexstanbury (notifications@github.com) wrote:

I'm loading the promises polyfilled version (localforage.js) but I am getting an error when using on this browser. The error is as follows:

TypeError: 'undefined' is not an object (evaluating 'adbinfo.db.transaction')

Any ideas?

**Comment by alexstanbury** [comment]
Well this is strange, it has suddenly started working without me changing anything.

For what it's worth, I'm using 1.2.4, not using private browsing mode and cookies are set to block from third parties.

It's my friend's device I am testing with, I opened Safari and opened a new tab (it wasn't in private mode as the browser colouring was light grey instead of dark) and browsed to my site and got the error. I got it every time upon refresh. I went to download Chrome to see if it was the same issue but before it completed I went back to safari and it worked...

I can now recreate it, if I open up private mode, select 'keep all' tabs and load the site, I get the aforementioned error as expected, the interesting thing is if I switch private mode off and again select 'keep all' tabs then the error persists even though I'm not in private mode any more.

I guess this is an iOS bug then, not sure what happened originally but I presume something funky with private mode interfering...I will update if I can provide any more info.

Cheers

**Comment by tofumatt** [comment]
Glad to hear it's working, though yeah that sounds like a super-weird bug.

Let me know if you run into anything reproducible or into this issue again. I'll close this for now, but don't be shy about issues.

Thanks for you detailed response!
