### ISSUE TITLE
LocalForage problem on Mac Chrome Version 45.0.2454.101 (64-bit) 

### ISSUE THREAD

**Issue by wudong** [mozilla/localForage#458]
I have an angular app running with localForage. 

But what puzzled me is that it sometime uses IndexedDB but sometime it uses Web SQL as the storage engine. 

In the resources tab in Chrome devtool, I can see both Web SQL and IndexDB contains the stored data and I don't know which one it is actually used. And it makes the app's behaviour somehow unpredictable on some situations. 

Can anyone explain why this would happens and how I can make it consistently use only one storage engine?

**Comment by tofumatt** [comment]
Sorry, could you clarify your issue?

Are you saying sometimes Chrome is using websql by default instead of indexeddb?

Are you using private browsing mode?

- tofumatt (Sent from mobile)

**Comment by wudong** [comment]
No issue.
I opened the chrome in development mode apparently the different device I
choose there will affect which storage backed localforage use.

Matthew Riley MacPherson <notifications@github.com>于2015年10月4日周日 13:32写道：

> Sorry, could you clarify your issue?
>
> Are you saying sometimes Chrome is using websql by default instead of
> indexeddb?
>
> Are you using private browsing mode?
>
> - tofumatt (Sent from mobile)
>

**Comment by tofumatt** [comment]
Cool. Thanks for letting me know.
