### ISSUE TITLE
localforage loaded through Systemjs AMD module loading does not work

### ISSUE THREAD

**Issue by jagandecapri** [mozilla/localForage#459]
I am using systemjs to load localforage to be used in AMD styled module.

My config is as such:

```
  System.config({
   .....
    paths: {
      localforage: 'bower_components/localforage/dist/localforage.js'
    }
   .....
  });
```

and I am trying to use it as below:

```
define(['localforage'], function(lf){
});
```

However, this throws an error saying 
`Uncaught (in promise) ReferenceError: require is not defined(…) localforage.js:2616`

Not sure how to get around this. Any help would be greatly appreciated. Thanks.

**Comment by tofumatt** [comment]
What version of localForage are you using (and where did you install it from)?

Sadly the docs in master might be a bit ahead of what’s in bower/NPM; I do need to push out a new tag but haven’t been quite able to get to it yet. Should be this week though.

If you install from master does it work?

**Comment by jagandecapri** [comment]
Hi @tofumatt , I am using    v1.2.10. I downloaded using bower. `bower install localforage`

I have not tried the master version yet.

**Comment by tofumatt** [comment]
If you could try master and see if that works it would be great.

If it does I'll aim to push a new version out today for you. Thanks.

- tofumatt (Sent from mobile)

**Comment by jagandecapri** [comment]
@tofumatt , yes it works. Please push a new version ASAP. Really need it. ;) 

Cheers. Thanks again @tofumatt .

**Comment by thgreasi** [comment]
I'm glad to hear that the `system-import-transformer` works for SystemJS!
We just need to add the tests now :)

**Comment by jagandecapri** [comment]
@thgreasi Nice to hear that :100:

**Comment by tofumatt** [comment]
Pushed 1.3 to NPM and GitHub (bower), so this should be fixed. 690c73df5e2263b171a23e440d285a642cdc6af4

**Comment by jagandecapri** [comment]
Thanks @tofumatt . It is working. :+1:
