### ISSUE TITLE
Chrome for iOS trouble

### ISSUE THREAD

**Issue by NathanWalker** [mozilla/localForage#460]
Does anyone know what the current status is with latest localForage on latest Chrome for iOS?
I couldn't find anything specific to this particular browser and having trouble getting localForage to work properly on Chrome for iOS.

Is it supported?
What is the fallback order on Chrome for iOS?
Does it use IndexedDB, WebSQL, or localStorage?

Thanks.

**Comment by tofumatt** [comment]
Chrome on iOS should be working as it is in Safari, as they share the same engine.

What version of Chrome, iOS, and localForage are you using?

It should use WebSQL regardless of versions; iOS IndexedDB support is broken.

**Comment by NathanWalker** [comment]
Chrome iOS: 45.0.2454.89
localForage: 1.2.10

Hmm ok that's helpful to know thank you. Do you know  what the WebSQL storage limit is on Chrome for iOS?

**Comment by tofumatt** [comment]
I don’t; I suspect again it’s the same as Safari (which is just under 5MB without prompting I think), but I’m not sure. How much are you trying to store?

**Comment by NathanWalker** [comment]
Well under 5Mb. ~ 900Kb... so weird. I'll keep investigating and close this until further notice. Thanks again.

**Comment by tofumatt** [comment]
Sure thing. Thanks for the info; if you do see specific errors traced back to localForage please file them here; if you eventually find your error and can share it here that’d be great. Maybe it’s a doc problem; if so I’d be happy to fix it.

Cheers!
