### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "system-import-transformer"

### ISSUE THREAD

**Issue by af7** [mozilla/localForage#462]
@tofumatt @thgreasi 

I get this error when building my project and using the v1.3.0 of localforage and webpack (with babel):

`Module build failed: ReferenceError: Unknown plugin "system-import-transformer"`

As per your `Readme` instructions, I use the following code to require localforage:

`require('script!localforage');`

I also tried `import localforage from 'localforage';` but I get the same error.

What needs to be changed with this setup?

Thank you!

**Comment by thgreasi** [comment]
Are you targeting the src folder?

**Comment by thgreasi** [comment]
In 1.3 you don't need to use `require('script!localforage');`, a plain require should work (we should change that in README). The dist files are precompiled es5 and are bundled with webpack.
If you try to make your own build using the src files then you should install the system-import-transformer.
https://github.com/thgreasi/babel-plugin-system-import-transformer

**Comment by af7** [comment]
@thgreasi 

Thanks, indeed I added the `"babel-plugin-system-import-transformer": "^1.1.4"` in my package.json and it now works. I would recommend that this is documented somewhere as other developers may also want to build solutions with webpack having localforage as an 'import'.
