### ISSUE TITLE
Promise misconfigured with Webpack

### ISSUE THREAD

**Issue by TCMiranda** [mozilla/localForage#465]
Guys, why???

When upgraded do 1.3, I got
![captura de tela de 2015-10-09 18 35 45](https://cloud.githubusercontent.com/assets/10077439/10406192/a49043dc-6eb4-11e5-9711-d7a399a6facc.png)

Which is this line
![captura de tela de 2015-10-09 18 40 42](https://cloud.githubusercontent.com/assets/10077439/10406285/490ea6d8-6eb5-11e5-976b-dcea85a81900.png)

Then I tried to fix my webpack config, so now, it's purely requiring it
`export { default as ldb } from 'localforage';`

I have defined Promise with webpack ProvidePlugin
![captura de tela de 2015-10-09 18 38 58](https://cloud.githubusercontent.com/assets/10077439/10406250/087c3180-6eb5-11e5-8abe-6fc63f479c4d.png)

And when debbuging:
![captura de tela de 2015-10-09 18 42 24](https://cloud.githubusercontent.com/assets/10077439/10406320/81490962-6eb5-11e5-8102-e518fc9ed49d.png)

`Promise` has two values, `Promise.Promise` seems to be the one I defined...

How can I fix this?

Thanks!

**Comment by tofumatt** [comment]
Just to be clear, you're including `dist/localforage.js`?

I would have thought to include localforage you'd want:

```js
import { default as ldb } from 'localforage';
```

Maybe I'm confused; sorry not super skilled with webpack yet :worried:

**Comment by TCMiranda** [comment]
Hey, yes, I checked that `'localforage'` is resolved to `dist/localforage.js`

Thanks!

**Comment by tofumatt** [comment]
Oh, did that solve the problem?

**Comment by TCMiranda** [comment]
No, sorry! I meant that I've checked it before... 

I cant tell if webpack is messing up with the polyfill included on the dist file with the one that I defined, or it is having problems defining it inside the code.

I'll try to debug it a little more...

**Comment by tofumatt** [comment]
Because localForage includes its own polyfill it might be a bit confused.

I wonder if importing src/localforage.js instead might work if you’re defining your own webpack config? If it does I can update the docs to say so…

If you try that let me know. Sorry about the error!

**Comment by TCMiranda** [comment]
To use the `src/localforage.js` I would have to allow it to use babel, and also all the files which it includes, so I think that I should instead figure out some way of validating this issue and help you wrap the loader

I'll be updating this!

**Comment by TCMiranda** [comment]
So, I dont think that the Promise polyfill can be used the way it is defined, could you confirm that to me?

https://github.com/mozilla/localForage/blob/master/dist/localforage.js#L690

They are in different scopes and different packaging machanisms. 

Not that it would resolve my problem, but I think you should remove the "concat" part of the build (to create the promise polyfill) and require it manually at `src/localforage.js`.

This way, webpack would automatically include the copy on the `dist/localforage.js`.

In this case, the `Promise` variable that I am able to use is the one I defined, which is misconfigured.

Unfortunately, even defining the `Promise` variable manually, the code breaks and gives me `"No available storage method found.(…)"` when I try to use it.

**Comment by thgreasi** [comment]
Hi there @TCMiranda 
If you're defining your own promise polyfill in your configuration, then how about targeting the .nopromises.js dist file? Requiring localforage with the webpack script loader plugin might also be a secondary solution for your problem.

In 1.3 we stopped requiring the promise polyfill inside the code since requiring polyfills is often criticised as an antipattern and should be avoided (the code should not be coupled with a polyfill, we have tooling for that). So, for the simple use case of the library ("drop it in and it should work") we are using concat to prepend the promise polyfill and prepare the exexution environment before actually defining localforage.
That way, we also allow people to repack the src files using a different or no polyfill. 

Waiting for your feedback!

**Comment by TCMiranda** [comment]
Hi @thgreasi 

I Managed to solve my problem when requiring localforage via script-loader after defined Promise globally, not by ProvidePlugin.

Thanks for the help!

**Comment by thgreasi** [comment]
Great! Glad to hear that!

On Sat, Oct 10, 2015, 23:14 Tiago de Carvalho Miranda <
notifications@github.com> wrote:

> Hi @thgreasi <https://github.com/thgreasi>
>
> I Managed to solve my problem when requiring localforage via script-loader
> after defined Promise globally, not by ProvidePlugin.
>
> Thanks for the help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/465#issuecomment-147122303>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer
