### ISSUE TITLE
ParseError: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by af7** [mozilla/localForage#466]
I use the latest localForage version (1.3.0).

I use browserify and Karma and babel.

When I start the tests I get the following error now:
![image](https://cloud.githubusercontent.com/assets/7850073/10450928/f9fa8672-71a5-11e5-9439-89481798999d.png)

This was not happening before (on 1.2.9). I was using the old instructions before too (no "import", etc.).

Any ideas why is this happening and what needs be changed? (possibly on my configuration, rather than on the library itself?)

Thank you.

**Comment by tofumatt** [comment]
If you’re importing localforage in your own webpack setup, I think you need to use babel’s “loose” config option to allow imports/exports in places other than top-level (which localforage currently uses).

Maybe we can get away from this in the future.

**Comment by af7** [comment]
Thanks @tofumatt, I read the page about `loose` in `babel` (http://babeljs.io/docs/advanced/loose/) but this does not seem to have anything to do with top-level imports/exports. It says something about Object.defineProperty. I tried it but it did not make any difference. I use browserify and babelify for the tests.
Are you sure that this is the proper approach?

**Comment by thgreasi** [comment]
ES6 code was actually introduced in v1.3, that's why the problem wasn't there in v1.2.
I guess that you are directly targeting the src files, is that true?
Since there is no ES6 code in the dist files (and of course no import exports).

On the other hand we have a .babelrc file that should instruct your builder to use our configuration for that file transformation!?!?

**Comment by af7** [comment]
Hi @thgreasi, I did not make any changes to the localforage package, so I do not target the 'src' files but the 'dist' ones.

If you ask if I have the .babelrc file then yes, I do have one, but it has only this code inside:

{
  "stage": 1
}

**Comment by thgreasi** [comment]
If you didn't change the localforage package at all, then you shouldn't be getting errors about the src files!?!?
Can you share your configuration?

**Comment by thgreasi** [comment]
If you didn't change the localforage package at all, then you shouldn't be getting errors related to the src files and es6. As you can see, the dist files do not contain any import/export statements and also our package.json targets the dist files.

Can you share your configurations and how you import localforage in your files?

**Comment by af7** [comment]
@thgrasi It appears that I did use the 'src' on a custom driver (this is how it had to be to work with 1.2.9).

Now that I did this change there, it works:

![image](https://cloud.githubusercontent.com/assets/7850073/10511471/15174682-7342-11e5-830c-17240c8c082c.png)

Thank you for your hints and direction.

**Comment by tofumatt** [comment]
You can now use `localforage.getSerializer()`, which returns a Promise that resolves with the serializer:

```js
localforage.getSerializer()
  .then(function(serializer) {
    console.log(serializer);
  });
```
