### ISSUE TITLE
How to access different dataStores on the same database

### ISSUE THREAD

**Issue by chocolatechipui** [mozilla/localForage#468]
You can create different databases with different dataStores (tables on WebSQL, dataStores on IndexedDB). For example, when localforage creates a database, it first creates the `local-forage-detect-blob-support` dataStore, followed by the one you create. Your API doesn't seem to offer any way to access a different dataStore using `setItem` and `getItem`. Is there someway to do this? Or is it required to make a separate localforage instance (a separate database) for each table/dataStore you want?

**Comment by thgreasi** [comment]
I think that a separate instance is the only way to have it work.

**Comment by tofumatt** [comment]
Yes, instance are self-contained by design; there is no way to share data between tables/dbs in the same instance.
