### ISSUE TITLE
any plans to allow searching for keys using regex etc?

### ISSUE THREAD

**Issue by siddo420** [mozilla/localForage#473]
my users may eventually end up having millions of records (possibly on sqlite) and I am not sure how efficient it'd be to traverse through all keys just to find some of them.

**Comment by tofumatt** [comment]
No plans but I would be open to any patch. It would need to look through all keys in localStorage but indexeddb and websql queries could be fast.

If you wanted to write a PR that would be great! :-)

- tofumatt (Sent from mobile)

**Comment by developit** [comment]
@siddo420 The nicest solution for this would be for someone (I might take a stab at it) to implement an indexing solution on top of `localForage`.  It could really just be an in-memory map of the keys you have in `localForage`, perhaps with "indexed" properties being stored as well.  Traversing that object in memory would be much more efficient than searching with data persisted to disk.

**Comment by tofumatt** [comment]
Right now this seems pretty out-of-scope for localForage. An entire indexing solution would be heavyweight and not in the spirit of the simplistic nature of localForage.

I think I'll close this for now, but a PR would be welcome in the future.
