### ISSUE TITLE
No available storage method found on Safari

### ISSUE THREAD

**Issue by bausmeier** [mozilla/localForage#474]
I am seeing the error "No available storage method found" on my production site using localForage for users on Safari 6.1 and 9.0. According to caniuse.com data those versions both support WebSQL and local storage, but I tried setting the driver to local storage explicitly and still see the errors. Any suggestions on what I might be doing wrong and how to fix it?

**Comment by tofumatt** [comment]
Any chance you’re using private browsing mode? You’re right; it shouldn’t be a problem for these browsers.

**Comment by bausmeier** [comment]
These errors are coming from Sentry so I can't really tell, but I have seen the same error from several users so I think private browsing is unlikely.

**Comment by bausmeier** [comment]
Any chance another error could be being caught here https://github.com/mozilla/localForage/blob/master/src/localforage.js#L374?

**Comment by tofumatt** [comment]
That’s where a lack of available drivers would end up, but it shouldn’t happen under normal use.

You’re only seeing this for a few users, right? Any chance you could share your initialisation code?

What happens when you test it in these browsers yourself?

**Comment by bausmeier** [comment]
I'm using browserify and not doing any special initialisation. All usage of local forage is done in a single file. The first few lines look like this:

```js
var LocalForage = require('localforage');

LocalForage.setDriver(LocalForage.LOCALSTORAGE);

exports.addItem = function(id, item) {
  return LocalForage.setItem(id, item);
};

exports.getItem = function(id) {
  return LocalForage.getItem(id);
};
```
Should I be doing explicit configuration?

I haven't been able to test with Safari, but have tested with a variety of other browsers both on desktop and on mobile, and I haven't come across any issues.

**Comment by tofumatt** [comment]
You shouldn’t need to do any explicit configuration unless you only want to be using localStorage. localForage by default picks the best driver available (for Safari that’s still WebSQL, as Safari’s IndexedDB implementation has some bugs right now).

Still, doesn’t explain why browsers are not finding the issue.

Again: private browsing mode really messes with localForage. If there aren’t clear steps to reproduce I’ll have to close this, but let me know if you find steps to reproduce.

I’ve seen a fair number of people just always browse privately, so it could be that. :O

**Comment by bausmeier** [comment]
Thanks for the help. I will just catch the error and show a warning that it won't work in private browsing mode.
