### ISSUE TITLE
Size prompt when name changes

### ISSUE THREAD

**Issue by willnwhite** [mozilla/localForage#479]
I'm getting the "Allow this website to use space on your disk?" prompt when I change the `localforage.name` from default, at least the first time after the website stores data in the browser (is registered in the browser's Website Data). Safari 9.0.

**Comment by tofumatt** [comment]
Sorry for the late response. Did you see this message the first time you used the default DB as well? I don't think the name should affect whether or not a message appears, but if you already created a DB in the past with the default name you might not be getting errors.

**Comment by willnwhite** [comment]
Not sure but I'll check this out next time I use localForage.

**Comment by nolanlawson** [comment]
Safari has a very unpredictable way of calculating the total available size. If you create too many databases with different names (even if they are very small, or don't have any data at all!) eventually Safari will complain.

If you are only running into this in your dev environment, then the best bet is to probably just clear all Safari data and start over. (See "Remove all website data..." in the Safari settings.)

**Comment by tofumatt** [comment]
Good to know.

If we can reproduce this from a fresh browser state, feel free to reopen, but I'll close this for now.
