### ISSUE TITLE
LF works in Chrome, not Firefox

### ISSUE THREAD

**Issue by tyl330** [mozilla/localForage#483]
I am sure I am missing something basic, but I cannot get LF to work in Firefox. Any data saved disappears immediately. I am trying to put together a multi-page app which depends on some fairly simple stored data. I would like to be able to use Firefox, but right now only Chrome retains the data. 

Details here: http://stackoverflow.com/questions/33973634/localforage-finds-data-in-chrome-not-in-firefox

Any help would be appreciated.

**Comment by tofumatt** [comment]
Hey there,

Sorry I didn't get to this until now: are you still finding issues with localForage in Firefox? If you're using the default settings, things should be working without issues.

Could you include the error you get?

**Comment by nolanlawson** [comment]
I think I may have figured out your issue; can you provide feedback? http://stackoverflow.com/questions/33973634/localforage-finds-data-in-chrome-not-in-firefox/36669583#36669583

**Comment by tofumatt** [comment]
Haven't heard anything back on this and my karma tests are passing on recent versions of Firefox, so I'm closing this. Interesting thought on `file://` in StackOverflow though neat that works now ^_^

Feel free to re-open if your issue wasn't solved or there was a fix you found 😄
