### ISSUE TITLE
what is the difference b/w name and storeName in configuration?

### ISSUE THREAD

**Issue by siddo420** [mozilla/localForage#484]
what is the difference b/w name and storeName in configuration?

What are the use cases for each?

**Comment by tofumatt** [comment]
Name will change the database name in IndexedDB/WebSQL and the storeName changes the storeName in IndexedDB and the table in WebSQL. It’s a bit of the IndexedDB underpinnings being exposed, I’ll admit.

**Comment by tofumatt** [comment]
Either will provide you with some separation of where your data is stored, but using different databases arguably isolates them more.

The use case ultimately is namespacing and data isolation, like with any database.

**Comment by siddo420** [comment]
I played with it a little more:

```
var db1 = localforage.createInstance({ name: 'DB-1' });
```
Then,
```
var db1_tbl1 = localforage.createInstance({ name: 'DB-1', storeName: 'tbl-1' });
db1_tbl1.keys(function(err, keys){ console.log(keys); }); <-- works but empty resultset b/c nothing is insrtd yt
```
However,
```
db1_tbl1.setItem( 'key' , 'val' ); 
```
fails with 
```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.(…)
  (anonymous function) @ localforage.js:1273
```
Also tried:
```
var db1_tbl1 = db1.createInstance({ storeName: 'tbl-1' }); //<-- works
```
fails on setItem again with the same err as abv.

Here is what the doc says about multiple instances:
```
You can create multiple instances of localForage that point to different stores using createInstance. All the configuration options used by config are supported.
```

**Comment by tofumatt** [comment]
Which browser(s) were you using? Seems related to #449.

**Comment by siddo420** [comment]
Chrome in Incognitio mode

**Comment by tofumatt** [comment]
FYI, private browsing in general has a lot of problems in localForage, because of how browsers handle localStorage/IndexedDB/WebSQL in private browsing mode.

Essentially localForage doesn't work well in incognito mode.
