### ISSUE TITLE
Firefox: disabling cookies breaks localforage

### ISSUE THREAD

**Issue by AshleyScirra** [mozilla/localForage#487]
In Firefox, go to options -> privacy. Select "use custom settings for history". Untick "accept cookies from sites".

Now localStorage access or indexedDB.open throws SecurityError. This breaks anything using localforage, since it appears to call this on startup and throws an uncaught exception.

This is a known issue in Firefox (see: https://bugzilla.mozilla.org/show_bug.cgi?id=748620). However it has apparently been like this for a long time. I think localforage should work around it: ideally if indexedDB fails to open, it will fall back to an in-memory store that is simply thrown away when navigating away. This maximises the chance the page will continue to work as normal.

**Comment by thgreasi** [comment]
We could use the [dummyStorageDriver](https://github.com/mozilla/localForage/blob/master/test/dummyStorageDriver.js) that is used for the [tests](https://github.com/mozilla/localForage/blob/master/test). We should probably refactor it to use the common [utils](https://github.com/mozilla/localForage/tree/master/src/utils) that we now use.

**Comment by thgreasi** [comment]
We could possibly clone it and use a more "professional" looking name, like MemoryStorage or something.
@AshleyScirra have you tested the [sessionStorageWrapper plugin](https://github.com/thgreasi/localForage-sessionStorageWrapper) in use case that you described?
I've been hearing that it works in some cases that localStorage fails.

**Comment by AshleyScirra** [comment]
Storing in memory has the advantage of avoiding any serializing to strings, and I can't remember but I thought Chrome Web Store apps dropped localStorage APIs in favour of IndexedDB/their own API. So I think a MemoryStorage driver would be useful to have as a workaround to Firefox's trigger-happy exceptions.

**Comment by thgreasi** [comment]
@AshleyScirra I totally agree with you, about in memory storage
**BUT** can you also answer to my previous question:
> @AshleyScirra have you tested the sessionStorageWrapper plugin in the use case that you described?

**Comment by AshleyScirra** [comment]
No, it doesn't work: localforage throws an unhandled exception testing for IndexedDB support, which leaves localforage undefined, so you can't get as far as a `defineDriver` call.

The problem is Firefox throws `SecurityError: The operation is insecure.` on this line, which only tests for IndexedDB's presence:

```js
var indexedDB = indexedDB || self.indexedDB || self.webkitIndexedDB || self.mozIndexedDB || self.OIndexedDB || self.msIndexedDB;
```

This is only referenced inside a try-catch statement further down, so it can be moved inside the try and it will detect it cannot use IndexedDB.

In this case all drivers fail to initialise and localforage is left with no driver. If I add the session storage driver, it incorrectly detects it can be used. Localforage will use it, but it too throws SecurityError upon any attempt to call sessionStorage.setItem/getItem!

So the only way to not have localforage completely broken in this case is to use an in-memory driver as a final fallback. Then despite Firefox's incredible awkwardness in this mode, data can be stored at least for the duration the page is open, maximising the chance the page can actually continue to function normally.

**Comment by thgreasi** [comment]
@AshleyScirra That's great!
Why don't you open a PR with this exact change?
PS: I can open a PRwith your suggested change tonight, if that's too much trouble for you.

**Comment by AshleyScirra** [comment]
I don't feel like I know this codebase well enough to implement a MemoryStorage driver, and moving the IndexedDB line only makes Firefox's failure case different, not better (loads with no driver rather than throwing exception). So could you make both changes?

**Comment by thgreasi** [comment]
Loading with no driver and rejecting the .ready() promise, is way better
than throwing an exception, since this allows developers to handle such
case and provide a custom driver.
I will open a PR for this tonight.

Regarding the in memory storage driver, I think we should track it in a
separate issue and get some feedback about it from @tofumatt.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment]
Sounds good.

I’m okay with the in-memory driver as a general fallback for no cookies—it also might fix our private browsing problems, not sure though.
