### ISSUE TITLE
Support for key queries: How to get items by a key starting with ...?

### ISSUE THREAD

**Issue by bennyn** [mozilla/localForage#491]
I am happily using localForage and the keys in my IndexedDB look like this:

Key | Value
--- | ---
User@1 | Homer
User@2 | Marge
User@3 | Lisa
User@4 | Bart
User@5 | Maggie
Location@1 | London
Location@2 | Paris
Location@3 | Rome

Now I want to get all items which have a key starting with `User@`. With the pure IndexedDB API I would use `IDBKeyRange.bound` but how to achieve this with localForage?

My current implementation (to grab all users) is this:

```javascript
var users = [];

var data = {
  'User@1': 'Homer',
  'User@2': 'Marge',
  'User@3': 'Lisa',
  'User@4': 'Bart',
  'User@5': 'Maggie',
  'Location@1': 'London',
  'Location@2': 'Paris',
  'Location@3': 'Rome'
};

// Clear database (delete items)
localforage.clear()
  // Fill database (save items)
  .then(function () {
    var keys = Object.keys(data);
    var promises = keys.map(function (key) {
      return localforage.setItem(key, data[key]);
    });
    return Promise.all(promises);
  })
  .then(function (values) {
    console.log('Saved items: ' + values.length, values);
  })
  .then(function () {
    // Filter database (query items)
    localforage.keys()
      .then(function (keys) {
        var pattern = 'User';
        return filtered_key = keys.filter(function (key) {
          return key.indexOf(pattern) > -1
        })
      })
      .then(function (filtered_key) {
        var promises = filtered_key.map(function (item) {
          return localforage.getItem(item);
        });
        return Promise.all(promises);
      })
      .then(function (values) {
        users = values;
        console.log('Filtered items: ' + users.length, users);
      });
  });
```

I am especially concerned about the `Filter database` part. Is there a smarter way of grabbing multiple items by a key wildcard?

**Comment by thgreasi** [comment]
Actually, there is [a plugin for exactly that](https://github.com/thgreasi/localForage-getItems) and it uses key ranges in IndexedDB and like queries in websql.

**Comment by thgreasi** [comment]
@bennyn Ooooooops!
Copy-Pasted the wrong repo url....
https://github.com/thgreasi/localForage-startsWith

**Comment by tofumatt** [comment]
Thanks for mentioning the plugin, looks like this is closed 😄
