### ISSUE TITLE
TypeScript typings, issue with 'default'

### ISSUE THREAD

**Issue by dsebastien** [mozilla/localForage#494]
Hello,

I'm currently trying to use localForage in a TypeScript project. As I've explained in #450 , the way the localForage typings file is currently implemented make it difficult for me to get auto completion.

I can get my IDE to work fine by defining the ambient module using the following syntax:

```
declare module "localforage" {
	export var localForage: LocalForage;
}
```

Instead of:

```
declare module "localforage" {
    var localforage: LocalForage;
    export default localforage;
}
```

Is the `default` export really necessary or could would you consider changing this?

**Comment by thgreasi** [comment]
I think that it is, since the default instance has to be attached to the
window object automatically when not loaded with a more modern way.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by dsebastien** [comment]
What do you mean by "modern way"?
Currently, I'm using JSPM & SystemJS, thus I would assume that I use a modern way :smile: 

Here's the output of my tests:

1) Without 'default' in the typings as I proposed:
```
declare module "localforage" {
	export var localForage: LocalForage;
}

and the following import:
```
import {localForage} from "localforage";
```

tsc outputs:
```
var localforage_1 = require("localforage");
```

2) With 'default' in the typings:
```
declare module "localforage" {
	var localForage: LocalForage;
	export default localForage;
}
```

and the following import:
```
import {default as localForage} from "localforage";
```

tsc outputs:
```
var localforage_1 = require("localforage");
```

Thus I don't think 'default' in the d.ts file make any difference apart for the way we can write the import (?)

**Comment by thgreasi** [comment]
I might be mistaken. Was referring to the default keyword in the .js file not the .ts. Sorry.
If it still matters, as "non-modern/traditional way" I was referring to including localforage in a script tag.

**Comment by dsebastien** [comment]
Script what? :D
Yep I'm sure you're right regarding localForage's js code, it certainly needs to have default in the exports.

Okay, I'll open a PR on DefinitelyTyped to propose the typings change and another one against this repository to update the readme.

**Comment by dsebastien** [comment]
Actually I overlooked something..

In the generated code, the require statement is as I've described above, but the usages of the associated variables are:

1) Without 'default' in the typings as I proposed: `localforage_1.localforage.setItem("key", "cool");`
2) With 'default' in the typings: `localforage_1.default.setItem("key", "cool");`

But my proposition remains relevant if I import as follows (the PR in this project needs to be adapted though): `const localForage = require("localforage");`

When I use require directly in the TS code, the generated code looks as it should: `localForage.setItem("key", "cool");`

I think this matches the explanations I found there:
* http://stackoverflow.com/questions/29596714/new-es6-syntax-for-importing-commonjs-amd-modules-i-e-import-foo-require
* http://www.jbrantly.com/es6-modules-with-typescript-and-webpack/ (CommonJS library - ES5 section):
    > TypeScript does not provide the same compatibility layer when importing CommonJS modules using ES6 syntax. In practice this means that you cannot use the "default import" syntax to import the module.

**Comment by dsebastien** [comment]
All done :)

**Comment by thgreasi** [comment]
@dsebastien  Hi there. I was recently creating a [sample Ionic 2 app](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonic2App) (on typescript 1.8) for [localForage-cordovaSQLiteDriver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver) and faced some difficulties while trying to import localforage. I ended up using:
```js
declare var require: Function;

const localforage:LocalForage = require('localforage');
const cordovaSQLiteDriver:LocalForageDriver = require('localforage-cordovasqlitedriver');
```

I'm sure that there is a better way than manually doing `declare var require: Function;`.
Can you suggest an improvement?

**Comment by nolanlawson** [comment]
We've had similar problems with PouchDB and TypeScript support recently. Maybe this can help: https://github.com/nolanlawson/pouchdb-ionic-2-typescript-demo

The trick seems to be `import * as LocalForage from 'localforage'`; apparently just doing `import LocalForage from 'localforage'` does not work in TypeScript's importer.

**Comment by thgreasi** [comment]
Hi Nolan.
Thanks for the example. I'm asking this for a sample ionic2 repo for
localforage-cordobaSqliteDriver, where I already tried:

> import * as LocalForage from 'localforage';
>
But even though the debugger showed that the correct object was imported
and referenced, I couldn't get the typings to work!?
My initial working approach was:
import * as localforageImport from 'localforage';
const localforage:LocalForage = localforageImport as any;

I ended up using the require() call mentioned earlier, after spotting some
docs mentioning that non es6 compliant module systems should stick to the
require() method. Typescript doesn't seem to use any helper method to
normalize the module default export (the way that babel does it) especially
not for the typings.

Thanks again and good morning from Greece.

PS: I think that creating an es6 dist file for localforage could improve
such use cases.

> --
*Thodoris Greasidis*

**Comment by nolanlawson** [comment]
Hm, that's odd, PouchDB has a CJS export as well, but you can still `import * as PouchDB`. It might be because we have a `jsnext:main` as well; I'm not sure.

Also for the typings, it shouldn't matter how you import it, although TBH I have no idea what TypeScript is doing here or what the best approach is.

Did you try `var localforage = require('localforage')` or `import localforage = require('localforage')`? TypeScript supports both (the latter being a TS-specific thing apparently).

**Comment by thgreasi** [comment]
Yes I tried those as well but I couldn't get automatic type recognition :(
Maybe it's something in my project's configuration. Thanks again.

> --
*Thodoris Greasidis*

**Comment by dagatsoin** [comment]
I modified the definition in https://github.com/dagatsoin/DefinitelyTyped/commit/024be6ae5426f1b463dc9d5675a86a0098a6ed0b#diff-e5ecc6c06f9fea487c7707db8d1ee5ae

Try this. I had the same problem as you with TS and Meteor.

**Comment by thgreasi** [comment]
@dagatsoin Hi there and thanks for the feedback!
Unfortuanately it didn't work for [my case](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonic2App), making
* `import * as localforageImport from 'localforage';` errors with `can't find module 'localforage'` and
* `const localforage:LocalForage = require('localforage');` errors with `can't find name 'LocalForage'`

What's your suggested way to do the import?

@nolanlawson found some time to check the sample ionic 2 pouchdb repo just now.
Unfortunatelly, even after defining some methods for PouchDB, `import * as PouchDB from 'pouchdb';` would only let me access `PouchDB.default`, even though the actual object was strored on the `PouchDB` variable (as noted by the `console.log()`).
`const PouchDB:PouchDB = require('pouchdb');` worked better for me.

**Comment by dagatsoin** [comment]
I did 
```
import * as LocalForage from 'localforage'
LocalForage.setDriver([LocalForage.INDEXEDDB, LocalForage.WEBSQL, LocalForage.LOCALSTORAGE]);
```
