### ISSUE TITLE
incompatible with projects that use Babel 6, as "loose" is now unknown option

### ISSUE THREAD

**Issue by jokeyrhyme** [mozilla/localForage#496]
I have a project that uses Babel 6. When I try to `require('localforage')`, I get the following babel compile error:

> ERROR in ./~/localforage/dist/localforage.js
> Module build failed: ReferenceError: [BABEL] redacted/node_modules/localforage/dist/localforage.js: Unknown option: redacted/node_modules/localforage/.babelrc.loose

The "loose" global option seems to be gone now: https://babeljs.io/docs/usage/options/

It looks like this is now supposed to be a per-plugin option, e.g: https://github.com/babel/babel/blob/6.4-stable/packages/babel-plugin-transform-es2015-for-of/test/fixtures/loose/options.json

This is loosely (pardon the pun) related to the following PRs:

- https://github.com/mozilla/localForage/pull/486
- https://github.com/mozilla/localForage/pull/390

Besides updating localForage to use Babel 6 as well, I'm not sure what other actions can be taken to resolve this.

**Comment by jokeyrhyme** [comment]
I am using webpack with babel-loader, and I've changed the way I use it, from:

`{ test: /\.jsx?$/, loader: 'babel-loader' }`

to:

`{ exclude: /localforage/, test: /\.jsx?$/, loader: 'babel-loader' }`

So my project can compile with Babel 6, without ever detecting the Babel 5 configuration that is supplied with the localforage npm module.

**Comment by thgreasi** [comment]
I already have a dev branch to upgrade to babel 6. I will continue my work
on it as soon as I get some free time.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
May we can just remove the configuration from the npm package?
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by jokeyrhyme** [comment]
The problem with removing the .babelrc file, is that babel will refuse to touch any of the files in the package. Which is fine for babel-using consumers who do `import localforage from 'localforage';`, but will break any consumers that do (for example) `import localforage from 'localforage/src/localforage';`.

This is only an interim problem, as you say, because:

1. babel 6 support is coming soon, anyway, and
2. ES2015 source files within an npm package will eventually be able to run on V8 / Node.js without babel

**Comment by thgreasi** [comment]
First of all using the src files is not officially supported by this repo
as far as I know but we are not trying to make it impossible either.
Since we can't support two different versions of babel at the same time
@tofumatt should have to decide whether we still provide a .babelrc file in
the distributed packages or not.

On Mon, Jan 11, 2016, 09:45 Ron Waldon <notifications@github.com> wrote:

> The problem with removing the .babelrc file, is that babel will refuse to
> touch any of the files in the package. Which is fine for babel-using
> consumers who do import localforage from 'localforage';, but will break
> any consumers that do (for example) import localforage from
> 'localforage/src/localforage';.
>
> This is only an interim problem, as you say, because:
>
>    1. babel 6 support is coming soon, anyway, and
>    2. ES2015 source files within an npm package will eventually be able
>    to run on V8 / Node.js without babel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/496#issuecomment-170454497>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment]
Existing versions ship with old Babel support, so I would say we should look forward and release a new version (1.4) with Babel 6 support.

- tofumatt

**Comment by jokeyrhyme** [comment]
Just found this: https://github.com/bkonkle/babel-preset-es2015-loose

**Comment by thgreasi** [comment]
:+1: 
Had some [experimentation with this some time ago](https://github.com/thgreasi/localForage/tree/babel6) and I think we can just skip that dependency and use its configuration directly on our `.babelrc` file. Moreover, I've been working on a [Babel6 compatible branch of system-import-transformer](https://github.com/thgreasi/babel-plugin-system-import-transformer/tree/babel6) that seems to work.
Unfortunately until next month I will not be able to dedicate enough time on this :disappointed:

**Comment by jokeyrhyme** [comment]
I have a PR #498 to solve this problem for any files in the "dist" directory within the package. If that is accepted, then you may wish to close this Issue.

However, if you wish to track babel 6 compatibility in general, then it may be worth leaving this Issue open regardless.

**Comment by thgreasi** [comment]
:+1:

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Just sharing my progress so far.
I have upgraded the system import transformer plugin for babel 6.
In my initial tests everything works except from the component build. That's probably because of the changes in the umd pattern that babel 6 uses.
Instead of using the es2015-loose preset, I will try to only define the plugins that are required to keep the changes of the dist files minimal.

**Comment by thgreasi** [comment]
@tofumatt it seems that [componentjs](https://github.com/componentjs/component) has been deprecated. Since it's the only test case that fails in my babel6 branch, what are your thoughts about removing them? If you agree, I could probably open a PR during the weekend.

**Comment by thgreasi** [comment]
It's probably the new/different/shorter UMD pattern of babel6 that makes things difficult for the component build.

**Comment by tofumatt** [comment]
I'm fine with removing it, if it's deprecated and causing issues.

- tofumatt
