### ISSUE TITLE
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]

### ISSUE THREAD

**Issue by c0debreaker** [mozilla/localForage#499]
We've been getting this warning since we started using LocalForage. We are using Bluebird.js

Here is the exact warning:

```
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at LocalForage.setDriver (http://localhost:8000/assets/js/vision.bundle.js:75077:31)
```

The exact code where it fails was pointing to this code in localforage.js
```
this._driverSet.then(callback, errorCallback);
```

**Comment by thgreasi** [comment]
If it is indeed a problem then we could do something like:
```js
// top level declaration
function nop() {};

// on every then callback
this._driverSet.then(callback || nop, errorCallback || nop);
```

**Comment by c0debreaker** [comment]
Cool. I'll try that code and let you know :)

**Comment by c0debreaker** [comment]
It worked though there were other codes that had similar issues. I applied the same fix and the errors went away though there are other warnings/errors that are still appearing in the console. I'm not sure if it's caused by LocalForage or not. I'll keep you posted.

**Comment by jameslk** [comment]
I'm running into this issue too

I would think this call:
https://github.com/mozilla/localForage/blob/9df0cdfb3d418278256854f208048908309f3011/src/localforage.js#L164

Would cause a problem with this line:
https://github.com/mozilla/localForage/blob/9df0cdfb3d418278256854f208048908309f3011/src/localforage.js#L388

Basically an undefined variable is being passed into then(). Am I missing something?

**Comment by judenaveenraj** [comment]
I'm getting this issue too with the following error:

Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at LocalForage._fullyReady [as ready] (http://localhost:8081/assets/build.js?b4332246c1065fe294d5:51239:14)

at the line :
promise.then(callback , callback );

Currently working using the nop workaround.

**Comment by thgreasi** [comment]
@judenaveenraj nice catch. Opened PR #588 for this.
