### ISSUE TITLE
SECURITY_ERR in PhantomJS (via grunt-contrib-jasmine)

### ISSUE THREAD

**Issue by olegbl** [mozilla/localForage#52]
PhantomJS seems to not like:

    var db = window.openDatabase(DB_NAME, DB_VERSION, STORE_NAME, DB_SIZE);

And throws:

    SECURITY_ERR: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

Putting that in a try catch and exiting early (as if !window.openDatabase happened) seems to prevent localforage from being defined. Problem for using this lib in a project that has unit tests being run through PhantomJS.

Note: PhantomJS is being run by grunt-contrib-jasmine in this instance.

**Comment by tofumatt** [comment]
This hasn't happened in some time, but more exciting should definitely stop when I merge #461.

I think I'll call this one closed. 😄
