### ISSUE TITLE
Chrome 49 - more than 256 simultaneous actions cause DOMException

### ISSUE THREAD

**Issue by ericeslinger** [mozilla/localForage#521]
Here's a simple test case: https://plnkr.co/edit/hKWtpq?p=preview

If you open this page on chrome 48 (stable), this works fine.
If you open this page on chrome 49 (beta), it fails. It looks like hitting the indexedDB with more than 256  simultaneous writes or reads causes some kind of overflow.

I don't know if this is something that needs to be fixed in localforage or chrome, but I'll report it on the chrome side as well.

**Comment by tofumatt** [comment]
Thanks for the report! Strikes me as a chrome bug on first look, as it doesn't happen anywhere else. So I'd guess it's a regression for them, but keep me posted, especially if we need to build a workaround.

**Comment by ericeslinger** [comment]
Yah, I was thinking about building something to debounce all my calls to localforage, to make sure I don't send more than 255 in at a time. This particular bug only happens in limited circumstances (when I need a list of all the users to filter by name in my system), and unfortunately the way I have architected my system, there's no single choke point - each data model object is independent and only knows about itself when it's time to pull data out of the localforage cache.

So funneling things through and making some kind of work queue is feasible, but just kind of annoying if it's a chrome thing only. Hopefully they fix it.

**Comment by ericeslinger** [comment]
Chromium issue - seems they did it on purpose. 

https://code.google.com/p/chromium/issues/detail?id=584768

**Comment by tofumatt** [comment]
Interesting. I guess their limit might just be a bit too aggressive then.

I've voted on the issue and subscribed to it. Thanks for filing the report. 👍

- tofumatt

**Comment by tofumatt** [comment]
Yay! They've [removed the throttle](https://code.google.com/p/chromium/issues/detail?id=584768) so next Canary should be fixed.
