### ISSUE TITLE
Local Forage data getting cleared on iOS devices

### ISSUE THREAD

**Issue by aniruddhbk** [mozilla/localForage#524]
I am using local forage 1.2.0 with angular-localforage 1.2.2 as part of an ionic app. Lately we are noticing some weird behaviour on iOS 8, 9, 9.1 that the storage is getting cleared after sometime. This does not happen on all iOS devices. The only common pattern is that these phones are little low in storage space ~ 500 MB. 

Why could this be happening? 

Its not happening on any of the android phones. But only with some iOS devices.

**Comment by tofumatt** [comment]
Sorry, but it sounds like there is a problem you can't consistency reproduce, from the sound of your issue. It is hard to help fix the problem when we don't know exactly what it is :-)

Any chance you could find the exact steps to reproduce your error and any error messages that go with it? Thanks!

- tofumatt

**Comment by dineshganti** [comment]
Hi tofumatt,
Here are the steps you can use to reproduce..

a) Take an iPhone (iOS 9, 9.1  does not matter). The space left on the device must be about 100-200MB 
b) Store something in localForage from any sample app.
c) Start shooting some video and after a while the iPhone gives a low memory alert...
d) Stop shooting the video. Kill the sample app.  Lock the phone and leave it for about 12 hours..
e) Unlock the phone after 12 hours and open the sample app. You will see that the localForage data has been completely wiped out..

**Comment by thgreasi** [comment]
So, it seems that it's the os that forces the browser to release the client side storage allocated.

**Comment by tofumatt** [comment]
Yup. At that point not sure there's much we can do about it, I don't think
this is within the scope of localforage. The OS will do this to native apps
as well, at least to a degree.
- tofumatt

**Comment by dineshganti** [comment]
Hi tofumatt. I agree to a certain extent. However, what can we do to avoid this?  Can you guide us?

Other native iPhone apps are not getting affected. Its only localForage data that's getting wiped out..

Is there any way for you guys to instruct iOS that this is important data that developers rely on and hence it shouldnt get deleted? 
Right now, if the data is getting wiped in cleanup, it means that iOS is treating this data as temporary storage or browser cache data etc, which is not important and can be removed..

Perhaps, you could test this at your end and also raise a ticket with Apple ?  LocalForage's stability and reliability will depend on this right?

**Comment by thgreasi** [comment]
Since you are working on top of Cordova, you can try to use the
[localForage-cordovaSQLiteDriver](
https://github.com/thgreasi/localForage-cordovaSQLiteDriver) plugin, which
will use the native DB of the device in the same way as native apps do.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by dineshganti** [comment]
Thanks thgreasi.

We are trying out the same. Will let you know if it works..

**Comment by bwalsh** [comment]
@dineshganti I believe I am running into a similar problem.  How did you resolve the issue?
Thanks for your time.

**Comment by guopengliang** [comment]
I believe this is not an issue specifically related to localForage. I also experienced this issue using native localStorage. When iOS system storage reaches to an almost full level, the user will be alerted with the "system storage low" warning, and iOS will clear all the localStorage data.

I am wondering is this also affecting the WebSQL storage? Has anyone experienced data loss using localforage.WEBSQL driver?

**Comment by swapkids** [comment]
@dineshganti Did the cordova/sqllite driver solve it for you?

**Comment by Bing573** [comment]
@guopengliang WEBSQL experienced the same issue
