### ISSUE TITLE
Docs improvement - callbacks/promise switcher

### ISSUE THREAD

**Issue by nolanlawson** [mozilla/localForage#534]
There was a thread on Twitter recently from @domenic about [newbies' difficulty using LocalForage](https://twitter.com/domenic/status/706220942096257024). I think it's a bit sad he was willing to look for alternatives, when really LocalForage ought to be a very beginner-friendly API. I suspect the real issue is a docs problem.

I have a couple suggestions, but I wanted to run them past @tofumatt first to get his thoughts:

1. **Replace the ["javascript/coffeescript" switch](http://mozilla.github.io/localForage/) in the docs with a "promise/callback" switch.** Coffeescript users are typically power users, so IME they don't need any extra documentation. Also the promise/callback switch idea was something we used [in the PouchDB docs](http://pouchdb.com/api.html#create_document), and I think the effect is really nice.
2. **Remove any documentation from the Github README.** Seriously, this can only serve to confuse people. Newbies aren't sure whether the "real" docs are in the README or on the site. Just make the README essentially a stub; point people to [the docs page](http://mozilla.github.io/localForage/).

**Comment by tofumatt** [comment]
I've thought about the second point for awhile but never got to it. Agreed though, that's be awesome.

First point is a good one. At the time I was really into CS but I'm less so now (especially with ES6), so ditching them for callbacks/promises would be cool.

I'm all for this, and will get to it myself at some point if no one else takes this.

Fixing #192 at the same time would be smart.

- tofumatt

**Comment by nolanlawson** [comment]
Cool, glad to know you agree. :) I'm happy to take up this issue now unless you want to, although I'm not so sure about how I would fix #192. (FWIW in PouchDB we also tried to get away from Jekyll/Ruby but ultimately gave up because Jekyll is so much more advanced than anything else we tried :stuck_out_tongue: )

**Comment by nolanlawson** [comment]
I'm already working on this, FWIW ("licking the cookie," so to speak ;))
