### ISSUE TITLE
Replace "promise" with "lie"

### ISSUE THREAD

**Issue by nolanlawson** [mozilla/localForage#537]
I've heard from at least a few people that the "large" size of LocalForage discourages them from wanting to use it. (8.6kB is not huge to me, but for some folks...)

Looking for quick wins, I noticed that localforage uses [promise](https://www.npmjs.com/package/promise) as its promise shim. While it has a less-nice name, [lie](https://github.com/calvinmetcalf/lie) is much smaller (and is what we use in PouchDB). A quick Browserify check says that `promise` is 4465 bytes, whereas `lie` is 1713 bytes. So you could shave off 31% of your size by just replacing that one module.

I looked through the code for an easy way to swap it out, but I admit I'm a little lost in the Webpack/System.js stuff as well as the `nopromise` build. In fact I can see `promise` in the `package.json`, but I can't tell where it's loaded at all. I started to write a PR, but kinda gave up halfway. :/

**Comment by tofumatt** [comment]
Oh, but still, this sounds like low-hanging fruit for me. I'll check it
out! (I'm off to China for a few days then flying home to the UK, but I can
maybe look this weekend)
- tofumatt

**Comment by nolanlawson** [comment]
Started looking into it in https://github.com/mozilla/localForage/pull/538, but there may be more work in there than I expected. :stuck_out_tongue:

**Comment by tofumatt** [comment]
Closed in #538. 👍
