### ISSUE TITLE
max limit on number of stores/instances?

### ISSUE THREAD

**Issue by siddo420** [mozilla/localForage#542]
Is there a known, max limit on number of stores created on any of the browser stores (websql, indexeddb etc)? 

I may need to create hundreds or thousands of them. 

Another question: 
Does .createInstance() properly separates/partitions data into separate databases and stores for all of the following data stores?
localforage.INDEXEDDB, localforage.WEBSQL, localforage.LOCALSTORAGE

**Comment by tofumatt** [comment]
For localforage, it simply creates keys that namesplace the days, but they
aren't really different stores technically speaking. They aren't visible to
each other in localForage though, if that's what you mean.

Regarding max number of stores... I don't know, but I would love to!
Browser vendors might specify such things in their docs but I don't think
anyone has run into a problem before.

If you do find any, please feel free to reopen this issue; we will either
find a workaround or document the limits, and see about increasing them as
well. Thanks!
- tofumatt
