### ISSUE TITLE
localforage w/ indexed DB not working after some app changes

### ISSUE THREAD

**Issue by trodrigues** [mozilla/localForage#544]
Hi there,

I have a smallish React based app, using react-router, hosted on github pages. Initially I was using hash based navigation because of GH pages and not being able to configure server based routes for pushState, but then I learned that you can hijack the 404.html to do so, which for my use case isn't that big of a deal, so I did that and switched to pushState navigation.

And then localforage stopped working.

It's really weird. There's no errors, rejected promises or anything that can give me even the slightest bit of insight as to what happened.

This is on Chrome, so I assume it was using IndexedDB by default. If I switch the driver to localStorage it works fine.

The app is available here: https://github.com/contentful/discovery-app-react

Localforage is only used to [save an object](https://github.com/contentful/discovery-app-react/blob/ce315c34d10d1a1a4139993b956d8fff81b7bd5c/src/components/settings/SettingsContainer.js#L20) and [retrieve that object](https://github.com/contentful/discovery-app-react/blob/ce315c34d10d1a1a4139993b956d8fff81b7bd5c/src/main.js#L46) 

The commit which broke things was [this one](https://github.com/contentful/discovery-app-react/blob/ce315c34d10d1a1a4139993b956d8fff81b7bd5c/src/main.js#L46) where I've configured react-router to use pushState based history, and had to set a `<base>` path because this is running on GH pages at http://contentful.github.io/discovery-app-react/

I tried googling around for any issues related to using a different base path together with IndexedDB but can't find anything useful on the subject.

Also, as @tofumatt said on IRC, this is probably not localforage related at all, and for my use case I'm totally fine with using localStorage anyway, but I'm wondering if I'm on to some weird browser bug here.

**Comment by nolanlawson** [comment]
Does it only occur on Chrome, or does it occur on Firefox and IE too? If it's only on Chrome, then it's very likely a browser bug and should probably be filed on Chromium.

**Comment by trodrigues** [comment]
I totally forgot to check that. Will try it out.

**Comment by trodrigues** [comment]
So after some testing it does seem to be an issue with Chrome in particular. I'll try to look for similar issues and put together a more standalone test case for this.

**Comment by KoenLav** [comment]
trodrigues is there any progress on this bug from Chrome?
