### ISSUE TITLE
Starting to see new DOMException in chrome 50

### ISSUE THREAD

**Issue by ericeslinger** [mozilla/localForage#545]
I don't actually know if this is a chrome bug, a localforage issue, or just my indexeddb getting too big or something, but I've started getting errors in my webapp (where I use localforage as a frontside cache). A call like 

    localforage.setItem('foo', 'bar')
    .then(function(){
      console.log('yay')
    }).catch(function(err){
      console.log(err);
    })

pauses for about 60 seconds and then resolves as an error with 'DOMException: Transaction timed out due to inactivity'. It started happening in chrome 50 I think, although it may have been happening earlier. There seems to be little else I can do to diagnose this - any suggestions?

**Comment by tofumatt** [comment]
Sorry for my late response here.

Are you still experiencing this issue? I tested recent versions of Chrome with a fair bit of data and couldn't reproduce. Can you build a test case for me to try?

**Comment by ericeslinger** [comment]
Nope, it went away with a later build, so I am going to assume this was a beta bug in indexeddb (I think it was overrunning its storage allocation somehow, b/c it only happened when my indexeddb was large) and is now fixed. Closing.
