### ISSUE TITLE
Question: share a data across multiple subdomain

### ISSUE THREAD

**Issue by no-more** [mozilla/localForage#548]
Hello,

I'm new to localforage and it looks very interesting. I would like to know if it's possible to share a data across multiple subdomain, for example 
 - login.mysite.com
 - app1.mysite.com
 - app2.mysite.com

I would like each of them to have their own storage, but I would like to be able to share some kind of token for authentication.

Is it possible? If not do you have a good advice on where I should look ?

Thanks a lot.
Best regards.

**Comment by nolanlawson** [comment]
Actually this is a browser storage security issue, and in fact none of LocalStorage/WebSQL/IndexedDB can be shared across subdomains. They are part of the "same origin policy" which sandboxes data. This is to prevent malicious sites from e.g. `malicious.geocities.com` spying on data from another site like `innocent.geocities.com`.

So the browser actually does not allow you to do this at all.

**Comment by no-more** [comment]
Hi,

Thanks but then how can I share a session across my subdomain? I don't want to use a sessionId in the url because this would mean it won't work if I open the url directly.
How does google and so many other sites handle this ?
This can't be handled by IP, nor coockies. I don't understand how it's working and how I should implement this.

Thanks a lot.

**Comment by nolanlawson** [comment]
> Thanks but then how can I share a session across my subdomain?

I believe the solution to that (e.g. what Google does) is to use cookies, because I believe you can specify cookies to work across subdomains. But I admit I'm not sure. In any case, I don't think localStorage/IndexedDB is the right solution for session management.

**Comment by skyrpex** [comment]
> In any case, I don't think localStorage/IndexedDB is the right solution for session management.

Exactly... sadly, your best bet is to rely on backend storage.

**Comment by no-more** [comment]
Hi,

> Exactly... sadly, your best bet is to rely on backend storage.
That's already what I'm doing, I'm just usually use local storage to store a data (some kind of token) to allow me to reconnect later without have to login again.
But my new need is that I want this to also work across multiple subdomain, without having to log in on each of them seperatly.

Thanks.

**Comment by nolanlawson** [comment]
Yeah, unfortunately for this use-case, storage across subdomains is not possible in any browser and is not spec'ed to ever be added. So this is something LocalForage cannot do. Whereas traditional cookie session management can be scoped to multiple subdomains.

**Comment by newbie78** [comment]
hi to all
see this https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
"Changing origin" part for the subdomain limitations

**Comment by juniarsofyan** [comment]
hi everyone, i have two different subdomains (mshop.bellezkin.com and bshop.bellezkin.com) each of them have localstorage data called carts. whenever i add an item to carts localstorage in mshop.bellezkin.com that carts data is also available in bshop.bellezkin.com. how to separate this carts data for each subdomain? Thanks in advance
(Sorry for my english)

**Comment by mrFANRA** [comment]
Dumn ... why they can't add access for subdomains like cookies. This can work with options, default option is closed only for one domain. They make it, but after 10 years.

Sorry for off-top, but this stupid limits make me cry.

**Comment by carycode** [comment]
Use cookies to share data across subdomains. [nolanlawson](https://github.com/nolanlawson) is right -- it is possible to specify cookies to work across subdomains.

"[Do I have to store tokens in cookies or localstorage or session?](https://stackoverflow.com/questions/54258233/do-i-have-to-store-tokens-in-cookies-or-localstorage-or-session/54258744#54258744)"
says that cookies are better for authentication tokens than localstorage, anyway.

"[Share cookie between subdomain and domain](https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain)" describes how to share cookies between subdomains,
such that any one of

* login.mysite.com
* app1.mysite.com
* app2.mysite.com

can set a cookie, and all the others can read that cookie.

When any of these servers sends in the HTTP response header:

    Set-Cookie: SID=31d4d96e407aad42; Path=/; Domain=mysite.com

the browser will return that cookie when fetching any resource from any path and any subdomain of "mysite.com", including all the above servers.

By default, though, if the server "app1.mysite.com" doesn't specify any domain in the HTTP response header -- if server "app1.mysite.com" sends *only*

    Set-Cookie: SID=31aa9d0; Path=/;

then the browser will return that cookie *only* to the server "app1.mysite.com".

Such sharing of cookies between subdomains is standardized in

* [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265) (which replaces the earlier subdomain cookie sharing standard [RFC 2109](https://datatracker.ietf.org/doc/html/rfc2109) ).

**Comment by charleskoehl** [comment]
If you want to make the localStorage object ignore the subdomain and be shared across all subdomains of the same domain, you can use the document.domain property. Here's how:

Set the document.domain property to the parent domain:
```js
document.domain = "example.com";
```
Use the localStorage object as you normally would:
```js
localStorage.setItem("key", "value");
var value = localStorage.getItem("key");
```
By setting the document.domain property to the parent domain, you are essentially telling the browser to treat all subdomains as if they were the same domain. This allows the localStorage object to be shared across all subdomains.

It's worth noting that the document.domain property should only be used in specific circumstances where cross-domain scripting or AJAX requests are necessary. It can be a security risk if used improperly, as it can allow scripts running on different domains to communicate with each other. Therefore, it's important to use this feature judiciously and only when necessary.
