### ISSUE TITLE
Synchronous and async at the same time

### ISSUE THREAD

**Issue by Itrulia** [mozilla/localForage#557]
Is there another way than requiring the libraries via AMD/CommonJS/SystemJS/etc.? 
Maybe a feature request? :D

**Comment by tofumatt** [comment]
Sorry, but localForage is an async-only library; the drivers underneath are async as is its entire API. This allows it to be very flexible.

If you'd like to avoid callbacks I'd suggest the Promises API which feels more linear even though it's async.

**Comment by Itrulia** [comment]
Nah its because sometimes I want the client to wait to avoid flashes in the UI for example, I definitely prefer promises
