### ISSUE TITLE
Self is not defined

### ISSUE THREAD

**Issue by fififofo** [mozilla/localForage#560]
When trying to include in react with:
import Localforage from "localforage"

I am getting the following error: 
root//node_modules/localforage/dist/localforage.js:1162
	})(typeof window !== 'undefined' ? window : self);

ReferenceError: self is not defined

Using browserify. This issue is probably related to #469

**Comment by nolanlawson** [comment]
This should be fixed with the next release, because we're using Browserify's definition of the global object instead of our own custom global object.

**Comment by tofumatt** [comment]
Released a new version (1.4.1), should be on npm once Travis builds it (should take < 30mins max).

Thanks for reminding me to release a new one 😄
