### ISSUE TITLE
v1.4.1 - Error: Cannot find module 'lie/polyfill'

### ISSUE THREAD

**Issue by godchuanz** [mozilla/localForage#562]
I believe this is a bug in v1.4.1 (nopromises), specifically at line 105.
`_dereq_('lie/polyfill');`

I suspect this line expects the client to be running CommonJS. On web browsers, this fails and localforage fails to load.

Once line 105 is removed, localforage appears to work.

**Comment by thgreasi** [comment]
Maybe we could add a ternary operator to check wether the Promise object is
already available.

Cc: @nolanlawson

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Just opened PR #563, please check.

**Comment by Aides359** [comment]
I am still experiencing this issue in IE11 :|

**Comment by thgreasi** [comment]
Are you using localforage.js or localforage.nopromises.js ?
[IE11 needs the Promise polyfill](http://caniuse.com/#search=promise) so please ensure that you are using localforage.js (or the min version).
