### ISSUE TITLE
pre-built warning in webpack bundle, /dist/localforage.js

### ISSUE THREAD

**Issue by HarryHH** [mozilla/localForage#567]
WARNING in ./~/localforage/dist/localforage.js
    Critical dependencies:
    7:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get bette
r results.
     @ ./~/localforage/dist/localforage.js 7:484-491

Can anyone fix that please?

**Comment by tofumatt** [comment]
But that file IS a pre-built JS file. This isn't an error, and I think it
might be possible to include src/localforage.js instead. But this isn't
something we can fix as dist/localforage.js IS a built file.

- tofumatt

**Comment by HarryHH** [comment]
i will add that to noParse then, thanks
