### ISSUE TITLE
function  removeItem

### ISSUE THREAD

**Issue by vorlon001** [mozilla/localForage#570]
function  removeItem doesn't delete a key in indexeddb.

var indexdb = localforage.createInstance({
  driver: localforage.INDEXEDDB,
  name: 'Rox'
});

indexdb.setItem("key", "value3");

indexdb.removeItem('key').then(function() {
    // Run this code once the key has been removed.
    console.log('Key is cleared!');
}).catch(function(err) {
    // This code runs if there were any errors
    console.log(err);
});

UserAgent:  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

**Comment by thgreasi** [comment]
You probably are missing a `then` chaining.
Couldn't reproduce, [seems to work for me](http://codepen.io/thgreasi/pen/WwVGzp).
Please fork if I have diverged from your use case.

**Comment by nolanlawson** [comment]
If you're unfamiliar with promises, you may want to check out [my blog post on the subject](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html). As @thgreasi says, you'll need to put `removeItem()` inside the `then()` call for `setItem()`, i.e.:

```js
indexdb.setItem("key", "value3").then(function () {
  return indexdb.removeItem('key');
}).then(function() {
  // done
}).catch(function(err) {
  console.log(err);
});
```

**Comment by konsumer** [comment]
Came across this randomly troubleshooting my own issue, and thought I would share these notes:

It works with ES6 & async/await, too, if you prefer a more sync-like look:

```js
import localforage from 'localforage'
const testOffline = async () => {
  await localforage.setItem('tester', 'YOUR TOKEN HERE')
  console.log('BEFORE:', await localforage.getItem('tester'))
  await localforage.removeItem('tester')
  console.log('AFTER:', await localforage.getItem('tester'))
}

// async function returns a promise
testOffline()
  .then(() => {
    console.log('DONE TESTING')
  })
```

Just have to remember to wrap your function with `async` and use `await` whenever you do something asynchronous.
