### ISSUE TITLE
Webpack thinks dist/localforage.js is pre-built

### ISSUE THREAD

**Issue by mlanin** [mozilla/localForage#577]
When using localforage with webpack I always have this warning:
```
WARNING in ./~/localforage/dist/localforage.js
Critical dependencies:
7:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/localforage/dist/localforage.js 7:484-491
```

**Comment by tofumatt** [comment]
Yes, this is normal, because `dist/localforage.js` _is_ a pre-built JavaScript file. This is fine and can be ignored.

**Comment by mlanin** [comment]
@tofumatt I know that it is ok, but such warnings are making mess in logs and console. Is there any chance to avoid it?

**Comment by tofumatt** [comment]
You could include `src/localforage.js` instead of `dist/localforage.js`,
but that’s not our recommended path. :-)

**Comment by petyappetrov** [comment]
@mlanin just add ignore
```
    module: {
        noParse: /node_modules\/localforage\/dist\/localforage.js/,
        loaders: [...],
```

**Comment by mlanin** [comment]
@petyappetrov Thanks, that worked!

**Comment by lagun4ik** [comment]
@petyappetrov Thanks!
If you use windows:
`/[\/\\]node_modules[\/\\]localforage[\/\\]dist[\/\\]localforage\.js$/`

**Comment by andersonmcook** [comment]
@petyappetrov Thanks!
I have 1.5.0 installed and had to change the regex to: 
`/node_modules\/localForage\/dist\/localforage.js/`
or better yet:
`/node_modules\/localforage\/dist\/localforage.js/i`
