### ISSUE TITLE
bower install issue

### ISSUE THREAD

**Issue by enguerran** [mozilla/localForage#583]
Hi,

I pull the project with bower like that:

`bower install localforage`

But the project I get is a little bit different that this one: https://github.com/xeriab/localForage

That project contains the same files in different cases in the dist folder: https://github.com/xeriab/localForage/tree/master/dist

What is wrong?

Mozilla do not publish the package to bower?
Do I need to do a PR to @xeriab to fix this?

_It is a problem as I use the package in a cordova project and the java compiler do not like same files with different cases._

**Comment by tofumatt** [comment]
If you `bower install localforage` it will install the version at this repository (https://github.com/mozilla/localForage).

If you want to install their version, you'll need to `bower install xeriab/localForage`, I believe. But I'm not a bower expert; frankly I'm considering dropping support as `npm` seems to work just fine and bower is just kind of a pain 😄

**Comment by enguerran** [comment]
You cannot close this issue as I explained I did `bower install localforage` and I got the xeriab version. Please check yourself with a `bower install localforage`.

Here is an extract of the bower.json file:
```
{
  "name": "HelloIonic",
  "private": true,
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.2.4",
    "ngCordova": "~0.1.23-alpha",
    "lodash": "~4.0.1",
    "a0-angular-storage": "^0.0.15",
    "localForage": "^1.4.2"
  },
  "dependencies": {
    "angular-ui-calendar": "^1.0.1",
    "angular-moment": "^0.10.3",
    "moment": "^2.13.0"
  }
}
```

I plusone you about bower and npm. But it does not explain why I got the xeriab version when I try to get the mozilla version.

**Comment by tofumatt** [comment]
You're capitalising the "f" in `localForage` in the package name, but I only have `localforage` registered.

That's incredibly silly/confusing of bower to allow that in my opinion (and a bit frustrating that @xeriab registered the caps one if he did intentionally, but I can't tell). I can't control that though.

Please use, exactly: `bower install localforage` and change the `F` to an `f` in your package.

<img width="497" alt="screenshot 2016-06-27 11 52 24" src="https://cloud.githubusercontent.com/assets/90871/16377410/dcc9bd6a-3c5d-11e6-82d7-a87b7ce60dd9.png">

**Comment by enguerran** [comment]
Oh, I see! My bad. I am very sorry about this issue, it was not really useful.

It is very silly of bower to let that happened.

**Comment by tofumatt** [comment]
Oh don’t worry about it! I can totally understand how it happened.

Agreed, it is silly. Don’t be shy about filing future issues, thanks for
bringing it to my attention at least so I know for the future :-)

**Comment by xeriab** [comment]
Sorry guys!

@enguerran I was a little bit sick to answer for that fault! 
I made a fork for a local project and added **sessionStorage** support for that fork!
I will remove it to make it clear for developers who are planning to use **localForage**.

**Comment by xeriab** [comment]
@tofumatt I did removed the fork and bower will no longer search for it!
Sorry again.

**Comment by tofumatt** [comment]
Thanks a lot! No worries, and thanks very much for removing it, helps
clarify things.

Sorry to hear you were sick. Glad you're feeling better! :-)

- Matthew Riley MacPherson | tofumatt.com

**Comment by enguerran** [comment]
Thanks @xeriab, no worry as we figured it out.
It was odd but now everything will be clearer.
